In [1]:
from pandas import pandas as pd

In [2]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is FA9B-A27A

 Directory of C:\Users\Amit Kumar Singh\class_notes\visualization all

20-04-2022  22:13    <DIR>          .
17-02-2022  19:07    <DIR>          ..
19-04-2022  18:14    <DIR>          .ipynb_checkpoints
06-01-2022  11:48         1,460,397 18.3.Plotly.7z
20-04-2022  22:14             4,338 html_data0.csv
20-04-2022  22:14             2,198 html_data1.csv
20-04-2022  22:14             4,176 html_data2.csv
20-04-2022  22:14             2,468 html_data3.csv
20-04-2022  22:14             3,273 html_data4.csv
20-04-2022  22:14             2,156 html_data5.csv
20-04-2022  22:14           125,625 my_picle_file
23-01-2022  15:08            28,597 numpy practice.ipynb
23-01-2022  14:57            59,551 numpy.ipynb
20-04-2022  00:20           294,141 pandas data manupulations.ipynb
19-04-2022  18:40         1,055,343 Pandas session 1 (1).ipynb
06-01-2022  16:13           871,956 Pandas session 1.ipynb
05-10-2021  14:20            32,627 Player.csv
20-04-2022  22:14            33,844 player_data.csv
20-04-2022  22:14             7,131 player_data1.csv
17-01-2022  16:06         1,113,578 plotly .ipynb
17-01-2022  18:45            10,135 rr.csv
17-01-2022  16:06           505,115 seaborn.ipynb
20-04-2022  22:14         3,156,704 test12.h5
17-01-2022  23:45           815,414 Untitled.ipynb
21-01-2022  15:34               588 Untitled1.ipynb
06-01-2022  11:54         1,155,356 Untitled12.ipynb
20-04-2022  22:13           955,439 Untitled2.ipynb
              24 File(s)     11,700,150 bytes
               3 Dir(s)  317,461,430,272 bytes free

In [3]:
df=pd.read_csv('Player.csv')

In [4]:
df

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [5]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is FA9B-A27A

 Directory of C:\Users\Amit Kumar Singh\class_notes\visualization all

20-04-2022  22:13    <DIR>          .
17-02-2022  19:07    <DIR>          ..
19-04-2022  18:14    <DIR>          .ipynb_checkpoints
06-01-2022  11:48         1,460,397 18.3.Plotly.7z
20-04-2022  22:14             4,338 html_data0.csv
20-04-2022  22:14             2,198 html_data1.csv
20-04-2022  22:14             4,176 html_data2.csv
20-04-2022  22:14             2,468 html_data3.csv
20-04-2022  22:14             3,273 html_data4.csv
20-04-2022  22:14             2,156 html_data5.csv
20-04-2022  22:14           125,625 my_picle_file
23-01-2022  15:08            28,597 numpy practice.ipynb
23-01-2022  14:57            59,551 numpy.ipynb
20-04-2022  00:20           294,141 pandas data manupulations.ipynb
19-04-2022  18:40         1,055,343 Pandas session 1 (1).ipynb
06-01-2022  16:13           871,956 Pandas session 1.ipynb
05-10-2021  14:20            32,627 Player.csv
20-04-2022  22:14            33,844 player_data.csv
20-04-2022  22:14             7,131 player_data1.csv
17-01-2022  16:06         1,113,578 plotly .ipynb
17-01-2022  18:45            10,135 rr.csv
17-01-2022  16:06           505,115 seaborn.ipynb
20-04-2022  22:14         3,156,704 test12.h5
17-01-2022  23:45           815,414 Untitled.ipynb
21-01-2022  15:34               588 Untitled1.ipynb
06-01-2022  11:54         1,155,356 Untitled12.ipynb
20-04-2022  22:13           955,439 Untitled2.ipynb
              24 File(s)     11,700,150 bytes
               3 Dir(s)  317,460,381,696 bytes free

In [6]:
df.head(10)

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
5,6,R Dravid,11-Jan-73,Right_Hand,Right-arm offbreak,India,0,NaN
6,7,W Jaffer,16-Feb-78,Right_Hand,Right-arm offbreak,India,0,NaN
7,8,V Kohli,5-Nov-88,Right_Hand,Right-arm medium,India,0,NaN
8,9,JH Kallis,16-Oct-75,Right_Hand,Right-arm fast-medium,South Africa,0,NaN
9,10,CL White,18-Aug-83,Right_Hand,Legbreak googly,Australia,0,NaN

In [7]:
df.tail(10)

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
513,514,I Shivram,NaN,NaN,NaN,India,1,NaN
514,515,SD Ranade,NaN,NaN,NaN,India,1,NaN
515,516,TH Wijewardene,NaN,NaN,NaN,Sri Lanka,1,NaN
516,517,AL Hill,NaN,NaN,NaN,New Zealand,1,NaN
517,518,RJ Tucker,NaN,NaN,NaN,Australia,1,NaN
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df.to_csv('player_data.csv')

In [10]:
df

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [11]:
df1=pd.read_csv('player_data.csv',sep=',',header='infer',names=['a','b','c','d','e','f','g','h'])

In [12]:
df1

,a,b,c,d,e,f,g,h
NaN,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0.0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1.0,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2.0,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3.0,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
...,...,...,...,...,...,...,...,...
518.0,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519.0,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520.0,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521.0,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522.0,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [13]:
df1=pd.read_csv('player_data.csv',sep=',')

In [14]:
df1

,Unnamed: 0,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...,...
518,518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [15]:
df1.describe()

       Unnamed: 0   Player_Id   Is_Umpire  Unnamed: 7
count  523.000000  523.000000  523.000000   12.000000
mean   261.000000  262.003824    0.099426    6.500000
std    151.121364  151.127981    0.299520    3.605551
min      0.000000    1.000000    0.000000    1.000000
25%    130.500000  131.500000    0.000000    3.750000
50%    261.000000  262.000000    0.000000    6.500000
75%    391.500000  392.500000    0.000000    9.250000
max    522.000000  524.000000    1.000000   12.000000

In [16]:
df1.dtypes

Unnamed: 0         int64
Player_Id          int64
Player_Name       object
DOB               object
Batting_Hand      object
Bowling_Skill     object
Country           object
Is_Umpire          int64
Unnamed: 7       float64
dtype: object

In [17]:
df.to_csv('player_data1.csv',index=False,sep='/',columns=['Player_Id','DOB'])

In [18]:
df.describe()

        Player_Id   Is_Umpire  Unnamed: 7
count  523.000000  523.000000   12.000000
mean   262.003824    0.099426    6.500000
std    151.127981    0.299520    3.605551
min      1.000000    0.000000    1.000000
25%    131.500000    0.000000    3.750000
50%    262.000000    0.000000    6.500000
75%    392.500000    0.000000    9.250000
max    524.000000    1.000000   12.000000

In [19]:
df.dtypes

Player_Id          int64
Player_Name       object
DOB               object
Batting_Hand      object
Bowling_Skill     object
Country           object
Is_Umpire          int64
Unnamed: 7       float64
dtype: object

In [20]:
a=df.columns[0:]

In [21]:
type(a)

pandas.core.indexes.base.Index

In [22]:
type(df[['DOB']])

pandas.core.frame.DataFrame

In [23]:
df[['DOB']]

           DOB
0     8-Jul-72
1    27-Sep-81
2    19-Dec-74
3    15-Jul-77
4    17-Oct-80
..         ...
518        NaN
519        NaN
520        NaN
521  14-Mar-92
522   8-Jul-94

[523 rows x 1 columns]

In [24]:
df2=pd.read_html("https://www.basketball-reference.com/players/i/ibakase01.html?utm_source=direct&utm_medium=Share&utm_campaign=ShareTool")

In [25]:
type(df2)

list

In [26]:
len(df2)

6

In [27]:
df2[0]

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2008-09,19.0,Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),...,Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain)
1,2009-10,20.0,OKC,NBA,PF,73,0,18.1,2.8,5.1,...,.630,1.9,3.5,5.4,0.1,0.3,1.3,0.9,2.7,6.3
2,2010-11,21.0,OKC,NBA,PF,82,44,27.0,4.1,7.5,...,.750,2.6,5.0,7.6,0.3,0.4,2.4,0.9,3.3,9.9
3,2011-12,22.0,OKC,NBA,PF,66,66,27.2,4.0,7.4,...,.661,2.9,4.6,7.5,0.4,0.5,3.7,1.2,2.7,9.1
4,2012-13,23.0,OKC,NBA,PF,80,80,31.1,5.6,9.7,...,.749,2.8,4.9,7.7,0.5,0.4,3.0,1.6,2.7,13.2
5,2013-14,24.0,OKC,NBA,PF,81,81,32.9,6.5,12.1,...,.784,2.8,6.0,8.8,1.0,0.5,2.7,1.5,2.9,15.1
6,2014-15,25.0,OKC,NBA,PF,64,64,33.1,5.8,12.3,...,.836,2.1,5.7,7.8,0.9,0.5,2.4,1.5,3.0,14.3
7,2015-16,26.0,OKC,NBA,PF,78,78,32.1,5.3,11.1,...,.752,1.8,5.0,6.8,0.8,0.5,1.9,1.4,2.7,12.6
8,2016-17,27.0,TOT,NBA,PF,79,79,30.7,6.0,12.4,...,.856,1.6,5.2,6.8,0.9,0.5,1.6,1.3,2.7,14.8
9,2016-17,27.0,ORL,NBA,PF,56,56,30.5,6.1,12.6,...,.846,1.8,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1
10,2016-17,27.0,TOR,NBA,PF,23,23,31.0,5.6,12.1,...,.882,1.3,5.5,6.8,0.7,0.3,1.4,1.7,3.3,14.2
11,2017-18,28.0,TOR,NBA,PF,76,76,27.5,5.0,10.3,...,.797,1.0,5.3,6.3,0.8,0.4,1.3,1.2,2.8,12.6
12,2018-19,29.0,TOR,NBA,C,74,51,27.2,6.3,11.9,...,.763,2.1,6.0,8.1,1.3,0.4,1.4,1.5,2.9,15.0
13,2019-20,30.0,TOR,NBA,C,55,27,27.0,6.2,12.2,...,.718,2.1,6.1,8.2,1.4,0.5,0.8,2.0,2.8,15.4
14,2020-21,31.0,LAC,NBA,C,41,39,23.3,4.5,8.9,...,.811,1.8,4.9,6.7,1.8,0.2,1.1,1.1,1.9,11.1
15,2021-22,32.0,TOT,NBA,"C,PF",54,12,16.2,2.7,5.5,...,.727,1.1,3.5,4.6,0.9,0.2,0.6,0.8,1.9,6.8
16,2021-22,32.0,LAC,NBA,C,35,10,15.4,2.7,5.5,...,.690,1.1,3.1,4.3,1.0,0.2,0.7,0.9,1.6,6.6
17,2021-22,32.0,MIL,NBA,PF,19,2,17.8,2.8,5.5,...,.800,1.2,4.1,5.3,0.7,0.2,0.4,0.5,2.4,7.0
18,Career,NaN,NaN,NBA,NaN,903,697,27.6,5.0,9.8,...,.758,2.1,5.1,7.2,0.8,0.4,1.9,1.3,2.7,12.1
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,7 seasons,NaN,OKC,NBA,NaN,524,413,28.8,4.9,9.3,...,.745,2.4,5.0,7.4,0.6,0.4,2.5,1.3,2.8,11.6
21,4 seasons,NaN,TOR,NBA,NaN,228,177,27.6,5.8,11.4,...,.768,1.7,5.7,7.4,1.1,0.4,1.2,1.5,2.8,14.2
22,2 seasons,NaN,LAC,NBA,NaN,76,49,19.6,3.7,7.3,...,.768,1.5,4.1,5.6,1.4,0.2,1.0,1.0,1.7,9.0
23,1 season,NaN,ORL,NBA,NaN,56,56,30.5,6.1,12.6,...,.846,1.8,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1
24,1 season,NaN,MIL,NBA,NaN,19,2,17.8,2.8,5.5,...,.800,1.2,4.1,5.3,0.7,0.2,0.4,0.5,2.4,7.0

In [28]:
for i in range(len(df2)):
    df2[i].to_csv('html_data{}.csv'.format(i))

In [29]:
titanic_data=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [30]:
type(titanic_data)

pandas.core.frame.DataFrame

In [31]:
amit="""
{"name":"amit","sex":["male","female"]
}
"""

In [32]:
import json

In [33]:
type(amit)

str

In [34]:
amit1 = json.loads(amit)

In [35]:
amit1

{'name': 'amit', 'sex': ['male', 'female']}

In [36]:
pd.DataFrame(amit1,columns=['sex'])

      sex
0    male
1  female

In [37]:
import requests

In [38]:
res=requests.get("https://api.github.com/repos/pandas-dev/pandas/issues")

In [39]:
type(res)

requests.models.Response

In [40]:
js=res.json()

In [41]:
js[1]['url']

'https://api.github.com/repos/pandas-dev/pandas/issues/46810'

In [42]:
for i in range(len(js)):
    print(js[i]['url'])

https://api.github.com/repos/pandas-dev/pandas/issues/46811
https://api.github.com/repos/pandas-dev/pandas/issues/46810
https://api.github.com/repos/pandas-dev/pandas/issues/46809
https://api.github.com/repos/pandas-dev/pandas/issues/46808
https://api.github.com/repos/pandas-dev/pandas/issues/46807
https://api.github.com/repos/pandas-dev/pandas/issues/46806
https://api.github.com/repos/pandas-dev/pandas/issues/46804
https://api.github.com/repos/pandas-dev/pandas/issues/46803
https://api.github.com/repos/pandas-dev/pandas/issues/46802
https://api.github.com/repos/pandas-dev/pandas/issues/46800
https://api.github.com/repos/pandas-dev/pandas/issues/46799
https://api.github.com/repos/pandas-dev/pandas/issues/46798
https://api.github.com/repos/pandas-dev/pandas/issues/46797
https://api.github.com/repos/pandas-dev/pandas/issues/46793
https://api.github.com/repos/pandas-dev/pandas/issues/46792
https://api.github.com/repos/pandas-dev/pandas/issues/46791
https://api.github.com/repos/pandas-dev/pandas/issues/46790
https://api.github.com/repos/pandas-dev/pandas/issues/46789
https://api.github.com/repos/pandas-dev/pandas/issues/46786
https://api.github.com/repos/pandas-dev/pandas/issues/46784
https://api.github.com/repos/pandas-dev/pandas/issues/46783
https://api.github.com/repos/pandas-dev/pandas/issues/46778
https://api.github.com/repos/pandas-dev/pandas/issues/46776
https://api.github.com/repos/pandas-dev/pandas/issues/46774
https://api.github.com/repos/pandas-dev/pandas/issues/46771
https://api.github.com/repos/pandas-dev/pandas/issues/46770
https://api.github.com/repos/pandas-dev/pandas/issues/46769
https://api.github.com/repos/pandas-dev/pandas/issues/46768
https://api.github.com/repos/pandas-dev/pandas/issues/46766
https://api.github.com/repos/pandas-dev/pandas/issues/46765

In [43]:
pd.DataFrame(js)

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46811,1209936718,PR_kwDOAA0YD842gR6J,46811,BUG: parsing nanoseconds incorrect resolution,...,2022-04-20T16:39:19Z,None,MEMBER,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46810,1209664145,I_kwDOAA0YD85IGgKR,46810,BUG: `pd.read_excel` writing numbers with .0 i...,...,2022-04-20T15:04:39Z,None,NONE,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46809,1209401729,I_kwDOAA0YD85IFgGB,46809,ENH: allow functions in `keep` parameter of `d...,...,2022-04-20T13:20:45Z,None,NONE,None,NaN,NaN,#### Is your feature request related to a prob...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46808,1209226761,I_kwDOAA0YD85IE1YJ,46808,BUG: TimeStamp index rolling problems,...,2022-04-20T06:35:44Z,None,NONE,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46807,1208928430,I_kwDOAA0YD85IDsiu,46807,BUG: Inconsistent result of in-place Series.re...,...,2022-04-19T22:39:14Z,None,CONTRIBUTOR,None,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46806,1208857290,PR_kwDOAA0YD842c2yI,46806,DOC: building page for nested methods doesn't ...,...,2022-04-20T07:22:16Z,None,MEMBER,None,False,{'url': 'https://api.github.com/repos/pandas-d...,closes #46804 \r\n\r\nLike this\r\n```\r\n pyt...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46804,1208841558,I_kwDOAA0YD85IDXVW,46804,DOC: building page for nested methods doesn't ...,...,2022-04-19T20:43:26Z,None,MEMBER,None,NaN,NaN,The following\r\n```\r\npython make.py --singl...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46803,1208773182,PR_kwDOAA0YD842ck7I,46803,REF: re-use Localizer for tz_convert_from_utc,...,2022-04-19T19:26:36Z,None,MEMBER,None,False,{'url': 'https://api.github.com/repos/pandas-d...,Also de-duplicate `tdata` construction and avo...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46802,1208577321,PR_kwDOAA0YD842b-lJ,46802,ENH: adding datetime default output formatting...,...,2022-04-19T16:12:59Z,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] partly addresses #46755\r\n- [x] [Tests ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46800,1208305496,I_kwDOAA0YD85IBUdY,46800,BUG: df.eval with inplace behavior changes aft...,...,2022-04-19T12:40:34Z,None,CONTRIBUTOR,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46799,1207499980,I_kwDOAA0YD85H-PzM,46799,BUG: Merge fails on nullable integer columns w...,...,2022-04-19T23:35:43Z,None,CONTRIBUTOR,None,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46798,1207172802,PR_kwDOAA0YD842Xj3P,46798,BUG: `DataFrameGroupBy.value_counts` includes ...,...,2022-04-18T21:11:22Z,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46357\r\n- [X] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46797,1206612518,I_kwDOAA0YD85H63Im,46797,BUG: pandas.cut doesnt respect to `precision...,...,2022-04-18T03:20:23Z,None,NONE,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46793,1206370745,I_kwDOAA0YD85H58G5,46793,WEB: Use mambaforge for the getting started in...,...,2022-04-17T13:07:21Z,None,MEMBER,None,NaN,NaN,We've got [this page](https://pandas.pydata.or...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46792,1206301209,PR_kwDOAA0YD842Uu8E,46792,ENH: Add numeric_only to resampler methods,...,2022-04-19T14:51:52Z,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #46442 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46791,1206170540,PR_kwDOAA0YD842UW62,46791,Change `mylen` function to account for NaN emp...,...,2022-04-19T03:06:01Z,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46084 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46790,1206164359,I_kwDOAA0YD85H5JuH,46790,ENH: Add option for `bold_column_headers` to `...,...,2022-04-18T07:21:23Z,None,CONTRIBUTOR,None,NaN,NaN,In the latest pandas version 1.4.2 there exist...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46789,1206141718,PR_kwDOAA0YD842UTSU,46789,BUG: .fillna(-1) does not work in pd.eval,...,2022-04-17T17:16:14Z,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,Adding ```self.value``` resolves the issue #46...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46786,1205872267,PR_kwDOAA0YD842TiuU,46786,TYP: CallableDynamicDoc,...,2022-04-15T20:35:48Z,None,CONTRIBUTOR,None,True,{'url': 'https://api.github.com/repos/pandas-d...,The more tricky parts of #46698.\r\n\r\nAdding...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46784,1205765682,PR_kwDOAA0YD842TO4h,46784,ENH: Added Index param to to_dict like in to_j...,...,2022-04-20T01:54:55Z,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46398 \r\n- [X] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46783,1205740295,I_kwDOAA0YD85H3iMH,46783,BUG: `dropna=False` not respected for groupby ...,...,2022-04-15T21:57:07Z,None,NONE,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46778,1204912401,PR_kwDOAA0YD842QdlT,46778,BUG: fixed buggy behavior in pivot_table with ...,...,2022-04-18T17:27:13Z,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #26568(Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46776,1204378879,I_kwDOAA0YD85HyVz_,46776,RLS: 2.0,...,2022-04-15T17:13:17Z,None,MEMBER,None,NaN,NaN,Tracking issue for the 2.0 release. (Note: pan...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46774,1204039393,PR_kwDOAA0YD842NvHH,46774,ENH: Create ArrowDtype,...,2022-04-18T22:27:49Z,None,MEMBER,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] All [code checks passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46771,1203768268,PR_kwDOAA0YD842M2rW,46771,BUG: date_range not excluding dates correctly ...,...,2022-04-18T11:55:04Z,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46331 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46770,1203632158,I_kwDOAA0YD85Hvfge,46770,"BUG: `CategoricalDtype(None, False)` does not ...",...,2022-04-14T11:24:46Z,None,CONTRIBUTOR,None,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46769,1203606102,I_kwDOAA0YD85HvZJW,46769,BUG: Pandas Index fails with `bitwise` ufuncs,...,2022-04-14T10:31:20Z,None,NONE,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46768,1203529564,I_kwDOAA0YD85HvGdc,46768,"DEPR: Deprecate daysinmonth, dayofweek, dayofyear",...,2022-04-14T11:16:55Z,None,CONTRIBUTOR,None,NaN,NaN,Based on original issue #1723 and https://gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46766,1203443826,PR_kwDOAA0YD842LxwD,46766,DOC: add examples to groupby.first,...,2022-04-18T17:52:00Z,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46765,1203409750,I_kwDOAA0YD85HupNW,46765,BUG: unable to read sftp urls despite fsspec s...,...,2022-04-13T20:04:59Z,None,NONE,None,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None

In [44]:
df5=pd.read_json('https://api.github.com/repos/pandas-dev/pandas/issues')

In [45]:
df5

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46811,1209936718,PR_kwDOAA0YD842gR6J,46811,BUG: parsing nanoseconds incorrect resolution,...,2022-04-20 16:39:19+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46810,1209664145,I_kwDOAA0YD85IGgKR,46810,BUG: `pd.read_excel` writing numbers with .0 i...,...,2022-04-20 15:04:39+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46809,1209401729,I_kwDOAA0YD85IFgGB,46809,ENH: allow functions in `keep` parameter of `d...,...,2022-04-20 13:20:45+00:00,NaT,NONE,NaN,NaN,NaN,#### Is your feature request related to a prob...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46808,1209226761,I_kwDOAA0YD85IE1YJ,46808,BUG: TimeStamp index rolling problems,...,2022-04-20 06:35:44+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46807,1208928430,I_kwDOAA0YD85IDsiu,46807,BUG: Inconsistent result of in-place Series.re...,...,2022-04-19 22:39:14+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46806,1208857290,PR_kwDOAA0YD842c2yI,46806,DOC: building page for nested methods doesn't ...,...,2022-04-20 07:22:16+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,closes #46804 \r\n\r\nLike this\r\n```\r\n pyt...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46804,1208841558,I_kwDOAA0YD85IDXVW,46804,DOC: building page for nested methods doesn't ...,...,2022-04-19 20:43:26+00:00,NaT,MEMBER,NaN,NaN,NaN,The following\r\n```\r\npython make.py --singl...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46803,1208773182,PR_kwDOAA0YD842ck7I,46803,REF: re-use Localizer for tz_convert_from_utc,...,2022-04-19 19:26:36+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Also de-duplicate `tdata` construction and avo...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46802,1208577321,PR_kwDOAA0YD842b-lJ,46802,ENH: adding datetime default output formatting...,...,2022-04-19 16:12:59+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] partly addresses #46755\r\n- [x] [Tests ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46800,1208305496,I_kwDOAA0YD85IBUdY,46800,BUG: df.eval with inplace behavior changes aft...,...,2022-04-19 12:40:34+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46799,1207499980,I_kwDOAA0YD85H-PzM,46799,BUG: Merge fails on nullable integer columns w...,...,2022-04-19 23:35:43+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46798,1207172802,PR_kwDOAA0YD842Xj3P,46798,BUG: `DataFrameGroupBy.value_counts` includes ...,...,2022-04-18 21:11:22+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46357\r\n- [X] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46797,1206612518,I_kwDOAA0YD85H63Im,46797,BUG: pandas.cut doesnt respect to `precision...,...,2022-04-18 03:20:23+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46793,1206370745,I_kwDOAA0YD85H58G5,46793,WEB: Use mambaforge for the getting started in...,...,2022-04-17 13:07:21+00:00,NaT,MEMBER,NaN,NaN,NaN,We've got [this page](https://pandas.pydata.or...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46792,1206301209,PR_kwDOAA0YD842Uu8E,46792,ENH: Add numeric_only to resampler methods,...,2022-04-19 14:51:52+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #46442 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46791,1206170540,PR_kwDOAA0YD842UW62,46791,Change `mylen` function to account for NaN emp...,...,2022-04-19 03:06:01+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46084 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46790,1206164359,I_kwDOAA0YD85H5JuH,46790,ENH: Add option for `bold_column_headers` to `...,...,2022-04-18 07:21:23+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,In the latest pandas version 1.4.2 there exist...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46789,1206141718,PR_kwDOAA0YD842UTSU,46789,BUG: .fillna(-1) does not work in pd.eval,...,2022-04-17 17:16:14+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Adding ```self.value``` resolves the issue #46...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46786,1205872267,PR_kwDOAA0YD842TiuU,46786,TYP: CallableDynamicDoc,...,2022-04-15 20:35:48+00:00,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,The more tricky parts of #46698.\r\n\r\nAdding...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46784,1205765682,PR_kwDOAA0YD842TO4h,46784,ENH: Added Index param to to_dict like in to_j...,...,2022-04-20 01:54:55+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46398 \r\n- [X] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46783,1205740295,I_kwDOAA0YD85H3iMH,46783,BUG: `dropna=False` not respected for groupby ...,...,2022-04-15 21:57:07+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46778,1204912401,PR_kwDOAA0YD842QdlT,46778,BUG: fixed buggy behavior in pivot_table with ...,...,2022-04-18 17:27:13+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #26568(Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46776,1204378879,I_kwDOAA0YD85HyVz_,46776,RLS: 2.0,...,2022-04-15 17:13:17+00:00,NaT,MEMBER,NaN,NaN,NaN,Tracking issue for the 2.0 release. (Note: pan...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46774,1204039393,PR_kwDOAA0YD842NvHH,46774,ENH: Create ArrowDtype,...,2022-04-18 22:27:49+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] All [code checks passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46771,1203768268,PR_kwDOAA0YD842M2rW,46771,BUG: date_range not excluding dates correctly ...,...,2022-04-18 11:55:04+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46331 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46770,1203632158,I_kwDOAA0YD85Hvfge,46770,"BUG: `CategoricalDtype(None, False)` does not ...",...,2022-04-14 11:24:46+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46769,1203606102,I_kwDOAA0YD85HvZJW,46769,BUG: Pandas Index fails with `bitwise` ufuncs,...,2022-04-14 10:31:20+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46768,1203529564,I_kwDOAA0YD85HvGdc,46768,"DEPR: Deprecate daysinmonth, dayofweek, dayofyear",...,2022-04-14 11:16:55+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,Based on original issue #1723 and https://gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46766,1203443826,PR_kwDOAA0YD842LxwD,46766,DOC: add examples to groupby.first,...,2022-04-18 17:52:00+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46765,1203409750,I_kwDOAA0YD85HupNW,46765,BUG: unable to read sftp urls despite fsspec s...,...,2022-04-13 20:04:59+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN

In [46]:
len(df5)

30

In [47]:
lis=[]
for i in range(len(js)):
    lis.append(js[i]['url'])

In [48]:
lis

['https://api.github.com/repos/pandas-dev/pandas/issues/46811',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46810',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46809',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46808',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46807',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46806',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46804',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46803',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46802',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46800',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46799',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46798',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46797',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46793',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46792',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46791',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46790',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46789',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46786',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46784',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46783',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46778',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46776',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46774',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46771',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46770',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46769',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46768',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46766',
 'https://api.github.com/repos/pandas-dev/pandas/issues/46765']

In [49]:
pd.DataFrame(lis)

                                                    0
0   https://api.github.com/repos/pandas-dev/pandas...
1   https://api.github.com/repos/pandas-dev/pandas...
2   https://api.github.com/repos/pandas-dev/pandas...
3   https://api.github.com/repos/pandas-dev/pandas...
4   https://api.github.com/repos/pandas-dev/pandas...
5   https://api.github.com/repos/pandas-dev/pandas...
6   https://api.github.com/repos/pandas-dev/pandas...
7   https://api.github.com/repos/pandas-dev/pandas...
8   https://api.github.com/repos/pandas-dev/pandas...
9   https://api.github.com/repos/pandas-dev/pandas...
10  https://api.github.com/repos/pandas-dev/pandas...
11  https://api.github.com/repos/pandas-dev/pandas...
12  https://api.github.com/repos/pandas-dev/pandas...
13  https://api.github.com/repos/pandas-dev/pandas...
14  https://api.github.com/repos/pandas-dev/pandas...
15  https://api.github.com/repos/pandas-dev/pandas...
16  https://api.github.com/repos/pandas-dev/pandas...
17  https://api.github.com/repos/pandas-dev/pandas...
18  https://api.github.com/repos/pandas-dev/pandas...
19  https://api.github.com/repos/pandas-dev/pandas...
20  https://api.github.com/repos/pandas-dev/pandas...
21  https://api.github.com/repos/pandas-dev/pandas...
22  https://api.github.com/repos/pandas-dev/pandas...
23  https://api.github.com/repos/pandas-dev/pandas...
24  https://api.github.com/repos/pandas-dev/pandas...
25  https://api.github.com/repos/pandas-dev/pandas...
26  https://api.github.com/repos/pandas-dev/pandas...
27  https://api.github.com/repos/pandas-dev/pandas...
28  https://api.github.com/repos/pandas-dev/pandas...
29  https://api.github.com/repos/pandas-dev/pandas...

In [50]:
df5

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46811,1209936718,PR_kwDOAA0YD842gR6J,46811,BUG: parsing nanoseconds incorrect resolution,...,2022-04-20 16:39:19+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46810,1209664145,I_kwDOAA0YD85IGgKR,46810,BUG: `pd.read_excel` writing numbers with .0 i...,...,2022-04-20 15:04:39+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46809,1209401729,I_kwDOAA0YD85IFgGB,46809,ENH: allow functions in `keep` parameter of `d...,...,2022-04-20 13:20:45+00:00,NaT,NONE,NaN,NaN,NaN,#### Is your feature request related to a prob...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46808,1209226761,I_kwDOAA0YD85IE1YJ,46808,BUG: TimeStamp index rolling problems,...,2022-04-20 06:35:44+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46807,1208928430,I_kwDOAA0YD85IDsiu,46807,BUG: Inconsistent result of in-place Series.re...,...,2022-04-19 22:39:14+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46806,1208857290,PR_kwDOAA0YD842c2yI,46806,DOC: building page for nested methods doesn't ...,...,2022-04-20 07:22:16+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,closes #46804 \r\n\r\nLike this\r\n```\r\n pyt...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46804,1208841558,I_kwDOAA0YD85IDXVW,46804,DOC: building page for nested methods doesn't ...,...,2022-04-19 20:43:26+00:00,NaT,MEMBER,NaN,NaN,NaN,The following\r\n```\r\npython make.py --singl...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46803,1208773182,PR_kwDOAA0YD842ck7I,46803,REF: re-use Localizer for tz_convert_from_utc,...,2022-04-19 19:26:36+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Also de-duplicate `tdata` construction and avo...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46802,1208577321,PR_kwDOAA0YD842b-lJ,46802,ENH: adding datetime default output formatting...,...,2022-04-19 16:12:59+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] partly addresses #46755\r\n- [x] [Tests ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46800,1208305496,I_kwDOAA0YD85IBUdY,46800,BUG: df.eval with inplace behavior changes aft...,...,2022-04-19 12:40:34+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46799,1207499980,I_kwDOAA0YD85H-PzM,46799,BUG: Merge fails on nullable integer columns w...,...,2022-04-19 23:35:43+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46798,1207172802,PR_kwDOAA0YD842Xj3P,46798,BUG: `DataFrameGroupBy.value_counts` includes ...,...,2022-04-18 21:11:22+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46357\r\n- [X] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46797,1206612518,I_kwDOAA0YD85H63Im,46797,BUG: pandas.cut doesnt respect to `precision...,...,2022-04-18 03:20:23+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46793,1206370745,I_kwDOAA0YD85H58G5,46793,WEB: Use mambaforge for the getting started in...,...,2022-04-17 13:07:21+00:00,NaT,MEMBER,NaN,NaN,NaN,We've got [this page](https://pandas.pydata.or...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46792,1206301209,PR_kwDOAA0YD842Uu8E,46792,ENH: Add numeric_only to resampler methods,...,2022-04-19 14:51:52+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #46442 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46791,1206170540,PR_kwDOAA0YD842UW62,46791,Change `mylen` function to account for NaN emp...,...,2022-04-19 03:06:01+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46084 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46790,1206164359,I_kwDOAA0YD85H5JuH,46790,ENH: Add option for `bold_column_headers` to `...,...,2022-04-18 07:21:23+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,In the latest pandas version 1.4.2 there exist...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46789,1206141718,PR_kwDOAA0YD842UTSU,46789,BUG: .fillna(-1) does not work in pd.eval,...,2022-04-17 17:16:14+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Adding ```self.value``` resolves the issue #46...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46786,1205872267,PR_kwDOAA0YD842TiuU,46786,TYP: CallableDynamicDoc,...,2022-04-15 20:35:48+00:00,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,The more tricky parts of #46698.\r\n\r\nAdding...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46784,1205765682,PR_kwDOAA0YD842TO4h,46784,ENH: Added Index param to to_dict like in to_j...,...,2022-04-20 01:54:55+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46398 \r\n- [X] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46783,1205740295,I_kwDOAA0YD85H3iMH,46783,BUG: `dropna=False` not respected for groupby ...,...,2022-04-15 21:57:07+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46778,1204912401,PR_kwDOAA0YD842QdlT,46778,BUG: fixed buggy behavior in pivot_table with ...,...,2022-04-18 17:27:13+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #26568(Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46776,1204378879,I_kwDOAA0YD85HyVz_,46776,RLS: 2.0,...,2022-04-15 17:13:17+00:00,NaT,MEMBER,NaN,NaN,NaN,Tracking issue for the 2.0 release. (Note: pan...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46774,1204039393,PR_kwDOAA0YD842NvHH,46774,ENH: Create ArrowDtype,...,2022-04-18 22:27:49+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] All [code checks passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46771,1203768268,PR_kwDOAA0YD842M2rW,46771,BUG: date_range not excluding dates correctly ...,...,2022-04-18 11:55:04+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46331 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46770,1203632158,I_kwDOAA0YD85Hvfge,46770,"BUG: `CategoricalDtype(None, False)` does not ...",...,2022-04-14 11:24:46+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46769,1203606102,I_kwDOAA0YD85HvZJW,46769,BUG: Pandas Index fails with `bitwise` ufuncs,...,2022-04-14 10:31:20+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46768,1203529564,I_kwDOAA0YD85HvGdc,46768,"DEPR: Deprecate daysinmonth, dayofweek, dayofyear",...,2022-04-14 11:16:55+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,Based on original issue #1723 and https://gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46766,1203443826,PR_kwDOAA0YD842LxwD,46766,DOC: add examples to groupby.first,...,2022-04-18 17:52:00+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46765,1203409750,I_kwDOAA0YD85HupNW,46765,BUG: unable to read sftp urls despite fsspec s...,...,2022-04-13 20:04:59+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN

In [51]:
user = []
res=requests.get('https://api.github.com/repos/pandas-dev/pandas/issues')
js=res.json()
for i in range(len(js)):
    user.append(js[i]['user'])

pd.DataFrame(user)

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
1,eliasmistler,26224290,MDQ6VXNlcjI2MjI0Mjkw,https://avatars.githubusercontent.com/u/262242...,,https://api.github.com/users/eliasmistler,https://github.com/eliasmistler,https://api.github.com/users/eliasmistler/foll...,https://api.github.com/users/eliasmistler/foll...,https://api.github.com/users/eliasmistler/gist...,https://api.github.com/users/eliasmistler/star...,https://api.github.com/users/eliasmistler/subs...,https://api.github.com/users/eliasmistler/orgs,https://api.github.com/users/eliasmistler/repos,https://api.github.com/users/eliasmistler/even...,https://api.github.com/users/eliasmistler/rece...,User,False
2,Neyri,28028777,MDQ6VXNlcjI4MDI4Nzc3,https://avatars.githubusercontent.com/u/280287...,,https://api.github.com/users/Neyri,https://github.com/Neyri,https://api.github.com/users/Neyri/followers,https://api.github.com/users/Neyri/following{/...,https://api.github.com/users/Neyri/gists{/gist...,https://api.github.com/users/Neyri/starred{/ow...,https://api.github.com/users/Neyri/subscriptions,https://api.github.com/users/Neyri/orgs,https://api.github.com/users/Neyri/repos,https://api.github.com/users/Neyri/events{/pri...,https://api.github.com/users/Neyri/received_ev...,User,False
3,mIgLLL,31037879,MDQ6VXNlcjMxMDM3ODc5,https://avatars.githubusercontent.com/u/310378...,,https://api.github.com/users/mIgLLL,https://github.com/mIgLLL,https://api.github.com/users/mIgLLL/followers,https://api.github.com/users/mIgLLL/following{...,https://api.github.com/users/mIgLLL/gists{/gis...,https://api.github.com/users/mIgLLL/starred{/o...,https://api.github.com/users/mIgLLL/subscriptions,https://api.github.com/users/mIgLLL/orgs,https://api.github.com/users/mIgLLL/repos,https://api.github.com/users/mIgLLL/events{/pr...,https://api.github.com/users/mIgLLL/received_e...,User,False
4,xinrong-databricks,47337188,MDQ6VXNlcjQ3MzM3MTg4,https://avatars.githubusercontent.com/u/473371...,,https://api.github.com/users/xinrong-databricks,https://github.com/xinrong-databricks,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,User,False
5,MarcoGorelli,33491632,MDQ6VXNlcjMzNDkxNjMy,https://avatars.githubusercontent.com/u/334916...,,https://api.github.com/users/MarcoGorelli,https://github.com/MarcoGorelli,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/gist...,https://api.github.com/users/MarcoGorelli/star...,https://api.github.com/users/MarcoGorelli/subs...,https://api.github.com/users/MarcoGorelli/orgs,https://api.github.com/users/MarcoGorelli/repos,https://api.github.com/users/MarcoGorelli/even...,https://api.github.com/users/MarcoGorelli/rece...,User,False
6,MarcoGorelli,33491632,MDQ6VXNlcjMzNDkxNjMy,https://avatars.githubusercontent.com/u/334916...,,https://api.github.com/users/MarcoGorelli,https://github.com/MarcoGorelli,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/gist...,https://api.github.com/users/MarcoGorelli/star...,https://api.github.com/users/MarcoGorelli/subs...,https://api.github.com/users/MarcoGorelli/orgs,https://api.github.com/users/MarcoGorelli/repos,https://api.github.com/users/MarcoGorelli/even...,https://api.github.com/users/MarcoGorelli/rece...,User,False
7,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
8,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
9,Yikun,1736354,MDQ6VXNlcjE3MzYzNTQ=,https://avatars.githubusercontent.com/u/173635...,,https://api.github.com/users/Yikun,https://github.com/Yikun,https://api.github.com/users/Yikun/followers,https://api.github.com/users/Yikun/following{/...,https://api.github.com/users/Yikun/gists{/gist...,https://api.github.com/users/Yikun/starred{/ow...,https://api.github.com/users/Yikun/subscriptions,https://api.github.com/users/Yikun/orgs,https://api.github.com/users/Yikun/repos,https://api.github.com/users/Yikun/events{/pri...,https://api.github.com/users/Yikun/received_ev...,User,False
10,NickCrews,10820686,MDQ6VXNlcjEwODIwNjg2,https://avatars.githubusercontent.com/u/108206...,,https://api.github.com/users/NickCrews,https://github.com/NickCrews,https://api.github.com/users/NickCrews/followers,https://api.github.com/users/NickCrews/followi...,https://api.github.com/users/NickCrews/gists{/...,https://api.github.com/users/NickCrews/starred...,https://api.github.com/users/NickCrews/subscri...,https://api.github.com/users/NickCrews/orgs,https://api.github.com/users/NickCrews/repos,https://api.github.com/users/NickCrews/events{...,https://api.github.com/users/NickCrews/receive...,User,False
11,LucasG0,44552904,MDQ6VXNlcjQ0NTUyOTA0,https://avatars.githubusercontent.com/u/445529...,,https://api.github.com/users/LucasG0,https://github.com/LucasG0,https://api.github.com/users/LucasG0/followers,https://api.github.com/users/LucasG0/following...,https://api.github.com/users/LucasG0/gists{/gi...,https://api.github.com/users/LucasG0/starred{/...,https://api.github.com/users/LucasG0/subscript...,https://api.github.com/users/LucasG0/orgs,https://api.github.com/users/LucasG0/repos,https://api.github.com/users/LucasG0/events{/p...,https://api.github.com/users/LucasG0/received_...,User,False
12,eromoe,3938751,MDQ6VXNlcjM5Mzg3NTE=,https://avatars.githubusercontent.com/u/393875...,,https://api.github.com/users/eromoe,https://github.com/eromoe,https://api.github.com/users/eromoe/followers,https://api.github.com/users/eromoe/following{...,https://api.github.com/users/eromoe/gists{/gis...,https://api.github.com/users/eromoe/starred{/o...,https://api.github.com/users/eromoe/subscriptions,https://api.github.com/users/eromoe/orgs,https://api.github.com/users/eromoe/repos,https://api.github.com/users/eromoe/events{/pr...,https://api.github.com/users/eromoe/received_e...,User,False
13,datapythonista,10058240,MDQ6VXNlcjEwMDU4MjQw,https://avatars.githubusercontent.com/u/100582...,,https://api.github.com/users/datapythonista,https://github.com/datapythonista,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/gi...,https://api.github.com/users/datapythonista/st...,https://api.github.com/users/datapythonista/su...,https://api.github.com/users/datapythonista/orgs,https://api.github.com/users/datapythonista/repos,https://api.github.com/users/datapythonista/ev...,https://api.github.com/users/datapythonista/re...,User,False
14,lorentzbao,19342156,MDQ6VXNlcjE5MzQyMTU2,https://avatars.githubusercontent.com/u/193421...,,https://api.github.com/users/lorentzbao,https://github.com/lorentzbao,https://api.github.com/users/lorentzbao/followers,https://api.github.com/users/lorentzbao/follow...,https://api.github.com/users/lorentzbao/gists{...,https://api.github.com/users/lorentzbao/starre...,https://api.github.com/users/lorentzbao/subscr...,https://api.github.com/users/lorentzbao/orgs,https://api.github.com/users/lorentzbao/repos,https://api.github.com/users/lorentzbao/events...,https://api.github.com/users/lorentzbao/receiv...,User,False
15,ehariri,21693509,MDQ6VXNlcjIxNjkzNTA5,https://avatars.githubusercontent.com/u/216935...,,https://api.github.com/users/ehariri,https://github.com/ehariri,https://api.github.com/users/ehariri/followers,https://api.github.com/users/ehariri/following...,https://api.github.com/users/ehariri/gists{/gi...,https://api.github.com/users/ehariri/starred{/...,https://api.github.com/users/ehariri/subscript...,https://api.github.com/users/ehariri/orgs,https://api.github.com/users/ehariri/repos,https://api.github.com/users/ehariri/events{/p...,https://api.github.com/users/ehariri/received_...,User,False
16,mosc9575,68053396,MDQ6VXNlcjY4MDUzMzk2,https://avatars.githubusercontent.com/u/680533...,,https://api.github.com/users/mosc9575,https://github.com/mosc9575,https://api.github.com/users/mosc9575/followers,https://api.github.com/users/mosc9575/followin...,https://api.github.com/users/mosc9575/gists{/g...,https://api.github.com/users/mosc9575/starred{...,https://api.github.com/users/mosc9575/subscrip...,https://api.github.com/users/mosc9575/orgs,https://api.github.com/users/mosc9575/repos,https://api.github.com/users/mosc9575/events{/...,https://api.github.com/users/mosc9575/received...,User,False
17,shyamsantoki,56479219,MDQ6VXNlcjU2NDc5MjE5,https://avatars.githubusercontent.com/u/564792...,,https://api.github.com/users/shyamsantoki,https://github.com/shyamsantoki,https://api.github.com/users/shyamsantoki/foll...,https://api.github.com/users/shyamsantoki/foll...,https://api.github.com/users/shyamsantoki/gist...,https://api.github.com/users/shyamsantoki/star...,https://api.github.com/users/shyamsantoki/subs...,https://api.github.com/users/shyamsantoki/orgs,https://api.github.com/users/shyamsantoki/repos,https://api.github.com/users/shyamsantoki/even...,https://api.github.com/users/shyamsantoki/rece...,User,False
18,twoertwein,6618166,MDQ6VXNlcjY2MTgxNjY=,https://avatars.githubusercontent.com/u/661816...,,https://api.github.com/users/twoertwein,https://github.com/twoertwein,https://api.github.com/users/twoertwein/followers,https://api.github.com/users/twoertwein/follow...,https://api.github.com/users/twoertwein/gists{...,https://api.github.com/users/twoertwein/starre...,https://api.github.com/users/twoertwein/subscr...,https://api.github.com/users/twoertwein/orgs,https://api.github.com/users/twoertwein/repos,https://api.github.com/users/twoertwein/events...,https://api.github.com/users/twoertwein/receiv...,User,False
19,vruthik,59946643,MDQ6VXNlcjU5OTQ2NjQz,https://avatars.githubusercontent.com/u/599466...,,https://api.github.com/users/vruthik,https://github.com/vruthik,https://api.github.com/users/vruthik/followers,https://api.github.com/users/vruthik/following...,https://api.github.com/users/vruthik/gists{/gi...,https://api.github.com/users/vruthik/starred{/...,https://api.github.com/users/vruthik/subscript...,https://api.github.com/users/vruthik/orgs,https://api.github.com/users/vruthik/repos,https://api.github.com/users/vruthik/events{/p...,https://api.github.com/users/vruthik/received_...,User,False
20,charlesbluca,20627856,MDQ6VXNlcjIwNjI3ODU2,https://avatars.githubusercontent.com/u/206278...,,https://api.github.com/users/charlesbluca,https://github.com/charlesbluca,https://api.github.com/users/charlesbluca/foll...,https://api.github.com/users/charlesbluca/foll...,https://api.github.com/users/charlesbluca/gist...,https://api.github.com/users/charlesbluca/star...,https://api.github.com/users/charlesbluca/subs...,https://api.github.com/users/charlesbluca/orgs,https://api.github.com/users/charlesbluca/repos,https://api.github.com/users/charlesbluca/even...,https://api.github.com/users/charlesbluca/rece...,User,False
21,andjhall,77794567,MDQ6VXNlcjc3Nzk0NTY3,https://avatars.githubusercontent.com/u/777945...,,https://api.github.com/users/andjhall,https://github.com/andjhall,https://api.github.com/users/andjhall/followers,https://api.github.com/users/andjhall/followin...,https://api.github.com/users/andjhall/gists{/g...,https://api.github.com/users/andjhall/starred{...,https://api.github.com/users/andjhall/subscrip...,https://api.github.com/users/andjhall/orgs,https://api.github.com/users/andjhall/repos,https://api.github.com/users/andjhall/events{/...,https://api.github.com/users/andjhall/received...,User,False
22,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
23,mroeschke,10647082,MDQ6VXNlcjEwNjQ3MDgy,https://avatars.githubusercontent.com/u/106470...,,https://api.github.com/users/mroeschke,https://github.com/mroeschke,https://api.github.com/users/mroeschke/followers,https://api.github.com/users/mroeschke/followi...,https://api.github.com/users/mroeschke/gists{/...,https://api.github.com/users/mroeschke/starred...,https://api.github.com/users/mroeschke/subscri...,https://api.github.com/users/mroeschke/orgs,https://api.github.com/users/mroeschke/repos,https://api.github.com/users/mroeschke/events{...,https://api.github.com/users/mroeschke/receive...,User,False
24,ma3da,34522496,MDQ6VXNlcjM0NTIyNDk2,https://avatars.githubusercontent.com/u/345224...,,https://api.github.com/users/ma3da,https://github.com/ma3da,https://api.github.com/users/ma3da/followers,https://api.github.com/users/ma3da/following{/...,https://api.github.com/users/ma3da/gists{/gist...,https://api.github.com/users/ma3da/starred{/ow...,https://api.github.com/users/ma3da/subscriptions,https://api.github.com/users/ma3da/orgs,https://api.github.com/users/ma3da/repos,https://api.github.com/users/ma3da/events{/pri...,https://api.github.com/users/ma3da/received_ev...,User,False
25,kwhkim,4476168,MDQ6VXNlcjQ0NzYxNjg=,https://avatars.githubusercontent.com/u/447616...,,https://api.github.com/users/kwhkim,https://github.com/kwhkim,https://api.github.com/users/kwhkim/followers,https://api.github.com/users/kwhkim/following{...,https://api.github.com/users/kwhkim/gists{/gis...,https://api.github.com/users/kwhkim/starred{/o...,https://api.github.com/users/kwhkim/subscriptions,https://api.github.com/users/kwhkim/orgs,https://api.github.com/users/kwhkim/repos,https://api.github.com/users/kwhkim/events{/pr...,https://api.github.com/users/kwhkim/received_e...,User,False
26,galipremsagar,11664259,MDQ6VXNlcjExNjY0MjU5,https://avatars.githubusercontent.com/u/116642...,,https://api.github.com/users/galipremsagar,https://github.com/galipremsagar,https://api.github.com/users/galipremsagar/fol...,https://api.github.com/users/galipremsagar/fol...,https://api.github.com/users/galipremsagar/gis...,https://api.github.com/users/galipremsagar/sta...,https://api.github.com/users/galipremsagar/sub...,https://api.github.com/users/galipremsagar/orgs,https://api.github.com/users/galipremsagar/repos,https://api.github.com/users/galipremsagar/eve...,https://api.github.com/users/galipremsagar/rec...,User,False
27,Dr-Irv,15113894,MDQ6VXNlcjE1MTEzODk0,https://avatars.githubusercontent.com/u/151138...,,https://api.github.com/users/Dr-Irv,https://github.com/Dr-Irv,https://api.github.com/users/Dr-Irv/followers,https://api.github.com/users/Dr-Irv/following{...,https://api.github.com/users/Dr-Irv/gists{/gis...,https://api.github.com/users/Dr-Irv/starred{/o...,https://api.github.com/users/Dr-Irv/subscriptions,https://api.github.com/users/Dr-Irv/orgs,https://api.github.com/users/Dr-Irv/repos,https://api.github.com/users/Dr-Irv/events{/pr...,https://api.github.com/users/Dr-Irv/received_e...,User,False
28,Moisan,31669,MDQ6VXNlcjMxNjY5,https://avatars.githubusercontent.com/u/31669?v=4,,https://api.github.com/users/Moisan,https://github.com/Moisan,https://api.github.com/users/Moisan/followers,https://api.github.com/users/Moisan/following{...,https://api.github.com/users/Moisan/gists{/gis...,https://api.github.com/users/Moisan/starred{/o...,https://api.github.com/users/Moisan/subscriptions,https://api.github.com/users/Moisan/orgs,https://api.github.com/users/Moisan/repos,https://api.github.com/users/Moisan/events{/pr...,https://api.github.com/users/Moisan/received_e...,User,False
29,maalgorium,18078278,MDQ6VXNlcjE4MDc4Mjc4,https://avatars.githubusercontent.com/u/180782...,,https://api.github.com/users/maalgorium,https://github.com/maalgorium,https://api.github.com/users/maalgorium/followers,https://api.github.com/users/maalgorium/follow...,https://api.github.com/users/maalgorium/gists{...,https://api.github.com/users/maalgorium/starre...,https://api.github.com/users/maalgorium/subscr...,https://api.github.com/users/maalgorium/orgs,https://api.github.com/users/maalgorium/repos,https://api.github.com/users/maalgorium/events...,https://api.github.com/users/maalgorium/receiv...,User,False

In [52]:
print('hiq')

hiq

In [53]:
user=[]
res=requests.get('https://api.github.com/repos/pandas-dev/pandas/issues')
js=res.json()
print(js)
for i in range(len(js)):
    user.append(js[i]['user'])

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46811', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46811/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46811/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46811/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46811', 'id': 1209936718, 'node_id': 'PR_kwDOAA0YD842gR6J', 'number': 46811, 'title': 'BUG: parsing nanoseconds incorrect resolution', 'user': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2022-04-20T16:38:25Z', 'updated_at': '2022-04-20T16:39:19Z', 'closed_at': None, 'author_association': 'MEMBER', 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46811', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46811', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46811.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46811.patch', 'merged_at': None}, 'body': '- [ ] closes #xxxx (Replace xxxx with the Github issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added an entry in the latest `doc/source/whatsnew/v1.5.0.rst` file if fixing a bug or adding a new feature.\r\n\r\nI ignored some c linter complaints bc this way the affected code is an exact match for the numpy code from which it is vendored.\r\n\r\nThis is broken off from a branch that fixes a couple of higher-level bugs.\r\n', 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46811/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46811/timeline', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46810', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46810/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46810/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46810/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/46810', 'id': 1209664145, 'node_id': 'I_kwDOAA0YD85IGgKR', 'number': 46810, 'title': 'BUG: `pd.read_excel` writing numbers with .0 in string column when using an Excel file downloaded from Google Sheets', 'user': {'login': 'eliasmistler', 'id': 26224290, 'node_id': 'MDQ6VXNlcjI2MjI0Mjkw', 'avatar_url': 'https://avatars.githubusercontent.com/u/26224290?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/eliasmistler', 'html_url': 'https://github.com/eliasmistler', 'followers_url': 'https://api.github.com/users/eliasmistler/followers', 'following_url': 'https://api.github.com/users/eliasmistler/following{/other_user}', 'gists_url': 'https://api.github.com/users/eliasmistler/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/eliasmistler/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/eliasmistler/subscriptions', 'organizations_url': 'https://api.github.com/users/eliasmistler/orgs', 'repos_url': 'https://api.github.com/users/eliasmistler/repos', 'events_url': 'https://api.github.com/users/eliasmistler/events{/privacy}', 'received_events_url': 'https://api.github.com/users/eliasmistler/received_events', 'type': 'User', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2022-04-20T13:08:11Z', 'updated_at': '2022-04-20T15:04:39Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': '### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\n\r\npath = "~/Downloads/test-from-gsheets.xlsx"\r\npd.read_excel(path)\n```\n\n\n### Issue Description\n\nIt seems like Pandas behaves differently with Excel files downloaded from Google Sheets than with those created in Excel. Namely, with files from Google Sheets, I get `.0` decimal points for columns with mixed data types (which does not happen in regular Excel files).\r\n\r\nTo reproduce: Create a new spreadsheet file in Google Drive and download as Excel. Can be as simple as one column, as long as it has numeric and string-like values:\r\n\r\n| Test   |\r\n| ------ |\r\n| ABC123 |\r\n| 234    |\r\n\r\nWhen reading this file with `pd.read_excel`, you get the following output (with the added `.0` in the string):\r\n\r\n| Test   |\r\n| ------ |\r\n| ABC123 |\r\n| 234.0  |\r\n\r\nFunnily enough, when I create the same file directly in Excel, I don\'t get the added `.0` and it works fine. I was even able to fix the behaviour by opening the downloaded file in Excel and saving it again.\n\n### Expected Behavior\n\nMixed type columns are read as `object` type, without trailing `.0`, independent of whether the Excel file was created in Excel or Google Sheets.\n\n### Installed Versions\n\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 4bfe3d07b4858144c219b9346329027024102ab6\r\npython           : 3.9.5.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 21.4.0\r\nVersion          : Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_GB.UTF-8\r\nLOCALE           : en_GB.UTF-8\r\n\r\npandas           : 1.4.2\r\nnumpy            : 1.22.3\r\npytz             : 2022.1\r\ndateutil         : 2.8.2\r\npip              : 22.0.4\r\nsetuptools       : 52.0.0.post20210125\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : 1.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nbrotli           :\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmarkupsafe       : None\r\nmatplotlib       : None\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsnappy           : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n</details>\r\n', 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46810/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46810/timeline', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46809', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46809/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46809/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46809/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/46809', 'id': 1209401729, 'node_id': 'I_kwDOAA0YD85IFgGB', 'number': 46809, 'title': 'ENH: allow functions in `keep` parameter of `drop_duplicates` to select which data to keep', 'user': {'login': 'Neyri', 'id': 28028777, 'node_id': 'MDQ6VXNlcjI4MDI4Nzc3', 'avatar_url': 'https://avatars.githubusercontent.com/u/28028777?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Neyri', 'html_url': 'https://github.com/Neyri', 'followers_url': 'https://api.github.com/users/Neyri/followers', 'following_url': 'https://api.github.com/users/Neyri/following{/other_user}', 'gists_url': 'https://api.github.com/users/Neyri/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Neyri/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Neyri/subscriptions', 'organizations_url': 'https://api.github.com/users/Neyri/orgs', 'repos_url': 'https://api.github.com/users/Neyri/repos', 'events_url': 'https://api.github.com/users/Neyri/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Neyri/received_events', 'type': 'User', 'site_admin': False}, 'labels': [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 2, 'created_at': '2022-04-20T09:12:11Z', 'updated_at': '2022-04-20T13:20:45Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': '#### Is your feature request related to a problem?\r\n\r\nI have a dataframe with several duplicated rows and I want to be able to select some kind of aggregate function when dropping duplicates. For instance I would like to keep the mean of a column, the max of another and so on...\r\nI figure this method would be more efficient than a `groupby().apply()` because the function would only be called on duplicates\r\n\r\n#### Describe the solution you\'d like\r\n\r\nFor me this would look like something like this :\r\n```python\r\ndef func_apply(duplicated_subset):\r\n    # This is just an example\r\n    row = duplicated_subset.iloc[0]\r\n    row["col1"] = duplicated_subset["col1"].mean()\r\n    row["col2"] = duplicated_subset["col2"].max()\r\n    return row\r\n\r\ndf.drop_duplicates(subset=[...], keep=func_apply)\r\n```\r\nThe function passed in parameter would receive a dataframe of rows duplicated and would be called for every duplicates. The function would return a row of the dataframe.\r\n\r\n#### API breaking implications\r\n\r\nNone\r\n\r\n#### Describe alternatives you\'ve considered\r\n\r\nFor now, to achieve this I use the following piece of code \r\n```python\r\nrows_duplicated = df[df.duplicated(subset=subset, keep=False)]\r\nrows_to_keep = df.drop_duplicates(subset=subset, keep=False)\r\nrows_clean = (\r\n    rows_duplicated.groupby(subset)\r\n    .apply(drop_method)\r\n    .reset_index(drop=True)\r\n)\r\ndf_filtered = pd.concat([rows_to_keep, rows_clean]).sort_index()\r\n```\r\nwhere `drop_method` can vary between what I want to perform. Here are some examples :\r\n```python\r\ndef drop_method(df_duplicates):\r\n    row =df_duplicates.iloc[0]\r\n    row["start_date"] = datetime_mean(\r\n        df_duplicates["start_date"]\r\n    )\r\n    row["end_date"] = datetime_mean(\r\n        df_duplicates["end_date"]\r\n    )\r\n    row["speed"] = df_duplicates["speed"].max()\r\n    return row\r\n\r\ndef drop_method(df_duplicates):\r\n    """\r\n    Returns the row of the dataframe with\r\n    the most number of values (not nan)\r\n    """\r\n    idx_most_values = df_duplicates.notna().sum(axis=1).idxmax()\r\n    return df_duplicates.loc[idx_most_values]\r\n\r\n```\r\n#### Additional context\r\n\r\nI believe this method could also answer [issue 25838](https://github.com/pandas-dev/pandas/issues/25838)\r\n', 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46809/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46809/timeline', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46808', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46808/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46808/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46808/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/46808', 'id': 1209226761, 'node_id': 'I_kwDOAA0YD85IE1YJ', 'number': 46808, 'title': 'BUG: TimeStamp index rolling problems', 'user': {'login': 'mIgLLL', 'id': 31037879, 'node_id': 'MDQ6VXNlcjMxMDM3ODc5', 'avatar_url': 'https://avatars.githubusercontent.com/u/31037879?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mIgLLL', 'html_url': 'https://github.com/mIgLLL', 'followers_url': 'https://api.github.com/users/mIgLLL/followers', 'following_url': 'https://api.github.com/users/mIgLLL/following{/other_user}', 'gists_url': 'https://api.github.com/users/mIgLLL/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mIgLLL/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mIgLLL/subscriptions', 'organizations_url': 'https://api.github.com/users/mIgLLL/orgs', 'repos_url': 'https://api.github.com/users/mIgLLL/repos', 'events_url': 'https://api.github.com/users/mIgLLL/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mIgLLL/received_events', 'type': 'User', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2022-04-20T06:35:44Z', 'updated_at': '2022-04-20T06:35:44Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': '### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\n\r\ndata = pd.date_range(start=\'1/1/2018\', periods=8).to_frame(name=\'date\')\r\ndata[\'symbol\'] = 1\r\n\r\ndata = data.append(data)\r\ndata.iloc[8:,1] = 2\r\n\r\ndata[\'value\'] = 1\r\n\r\n## total 16 days ( ValueError: index must be monotonic )\r\nroll_mean = data.groupby(\'symbol\')[\'value\'].rolling(\'2d\').mean()\r\n\r\n## only second 8 days (Only globally monotonic index worked)\r\nroll_mean = data.iloc[8:,:].groupby(\'symbol\')[\'value\'].rolling(\'2d\').mean()\n```\n\n\n### Issue Description\n\nThere is a problem that the rolling function requires the index to be monotonic in the newest version of pandas (1.4.1). It start to require a globally monotonic index for rolling function, which is quite unreasonable for timestamp index. Panel data are used quite commonly! The global monotonic requirement should instead be taken of by " within group monotonic". \r\n\n\n### Expected Behavior\n\nreturn to the previous "within-group monotonic".\n\n### Installed Versions\n\n<details>\r\n\r\nReplace this line with the output of pd.show_versions()\r\n\r\n</details>\r\n\r\n* I have reinstall the pandas as 1.3.5 to avoid this problem, 1.4.1 is the version that cause this problem.\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d\r\npython           : 3.9.12.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19042\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : zh_CN\r\nLOCALE           : Chinese (Simplified)_China.936\r\n\r\npandas           : 1.3.5\r\nnumpy            : 1.20.3\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 21.2.4\r\nsetuptools       : 61.2.0\r\nCython           : 0.29.28\r\npytest           : 7.1.1\r\nhypothesis       : None\r\nsphinx           : 4.4.0\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 3.0.3\r\nlxml.etree       : 4.8.0\r\nhtml5lib         : 1.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.3\r\nIPython          : 8.2.0\r\npandas_datareader: 0.10.0\r\nbs4              : 4.10.0\r\nbottleneck       : 1.3.4\r\nfsspec           : 2022.02.0\r\nfastparquet      : 0.8.0\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumexpr          : 2.8.1\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : 7.0.0\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.7.3\r\nsqlalchemy       : 1.4.32\r\ntables           : 3.6.1\r\ntabulate         : 0.8.9\r\nxarray           : None\r\nxlrd             : 2.0.1\r\nxlwt             : 1.3.0\r\nnumba            : 0.54.1', 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46808/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart

In [54]:
pd.DataFrame([js[i]['user'] for i in range(len(js))])

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
1,eliasmistler,26224290,MDQ6VXNlcjI2MjI0Mjkw,https://avatars.githubusercontent.com/u/262242...,,https://api.github.com/users/eliasmistler,https://github.com/eliasmistler,https://api.github.com/users/eliasmistler/foll...,https://api.github.com/users/eliasmistler/foll...,https://api.github.com/users/eliasmistler/gist...,https://api.github.com/users/eliasmistler/star...,https://api.github.com/users/eliasmistler/subs...,https://api.github.com/users/eliasmistler/orgs,https://api.github.com/users/eliasmistler/repos,https://api.github.com/users/eliasmistler/even...,https://api.github.com/users/eliasmistler/rece...,User,False
2,Neyri,28028777,MDQ6VXNlcjI4MDI4Nzc3,https://avatars.githubusercontent.com/u/280287...,,https://api.github.com/users/Neyri,https://github.com/Neyri,https://api.github.com/users/Neyri/followers,https://api.github.com/users/Neyri/following{/...,https://api.github.com/users/Neyri/gists{/gist...,https://api.github.com/users/Neyri/starred{/ow...,https://api.github.com/users/Neyri/subscriptions,https://api.github.com/users/Neyri/orgs,https://api.github.com/users/Neyri/repos,https://api.github.com/users/Neyri/events{/pri...,https://api.github.com/users/Neyri/received_ev...,User,False
3,mIgLLL,31037879,MDQ6VXNlcjMxMDM3ODc5,https://avatars.githubusercontent.com/u/310378...,,https://api.github.com/users/mIgLLL,https://github.com/mIgLLL,https://api.github.com/users/mIgLLL/followers,https://api.github.com/users/mIgLLL/following{...,https://api.github.com/users/mIgLLL/gists{/gis...,https://api.github.com/users/mIgLLL/starred{/o...,https://api.github.com/users/mIgLLL/subscriptions,https://api.github.com/users/mIgLLL/orgs,https://api.github.com/users/mIgLLL/repos,https://api.github.com/users/mIgLLL/events{/pr...,https://api.github.com/users/mIgLLL/received_e...,User,False
4,xinrong-databricks,47337188,MDQ6VXNlcjQ3MzM3MTg4,https://avatars.githubusercontent.com/u/473371...,,https://api.github.com/users/xinrong-databricks,https://github.com/xinrong-databricks,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,https://api.github.com/users/xinrong-databrick...,User,False
5,MarcoGorelli,33491632,MDQ6VXNlcjMzNDkxNjMy,https://avatars.githubusercontent.com/u/334916...,,https://api.github.com/users/MarcoGorelli,https://github.com/MarcoGorelli,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/gist...,https://api.github.com/users/MarcoGorelli/star...,https://api.github.com/users/MarcoGorelli/subs...,https://api.github.com/users/MarcoGorelli/orgs,https://api.github.com/users/MarcoGorelli/repos,https://api.github.com/users/MarcoGorelli/even...,https://api.github.com/users/MarcoGorelli/rece...,User,False
6,MarcoGorelli,33491632,MDQ6VXNlcjMzNDkxNjMy,https://avatars.githubusercontent.com/u/334916...,,https://api.github.com/users/MarcoGorelli,https://github.com/MarcoGorelli,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/gist...,https://api.github.com/users/MarcoGorelli/star...,https://api.github.com/users/MarcoGorelli/subs...,https://api.github.com/users/MarcoGorelli/orgs,https://api.github.com/users/MarcoGorelli/repos,https://api.github.com/users/MarcoGorelli/even...,https://api.github.com/users/MarcoGorelli/rece...,User,False
7,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
8,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
9,Yikun,1736354,MDQ6VXNlcjE3MzYzNTQ=,https://avatars.githubusercontent.com/u/173635...,,https://api.github.com/users/Yikun,https://github.com/Yikun,https://api.github.com/users/Yikun/followers,https://api.github.com/users/Yikun/following{/...,https://api.github.com/users/Yikun/gists{/gist...,https://api.github.com/users/Yikun/starred{/ow...,https://api.github.com/users/Yikun/subscriptions,https://api.github.com/users/Yikun/orgs,https://api.github.com/users/Yikun/repos,https://api.github.com/users/Yikun/events{/pri...,https://api.github.com/users/Yikun/received_ev...,User,False
10,NickCrews,10820686,MDQ6VXNlcjEwODIwNjg2,https://avatars.githubusercontent.com/u/108206...,,https://api.github.com/users/NickCrews,https://github.com/NickCrews,https://api.github.com/users/NickCrews/followers,https://api.github.com/users/NickCrews/followi...,https://api.github.com/users/NickCrews/gists{/...,https://api.github.com/users/NickCrews/starred...,https://api.github.com/users/NickCrews/subscri...,https://api.github.com/users/NickCrews/orgs,https://api.github.com/users/NickCrews/repos,https://api.github.com/users/NickCrews/events{...,https://api.github.com/users/NickCrews/receive...,User,False
11,LucasG0,44552904,MDQ6VXNlcjQ0NTUyOTA0,https://avatars.githubusercontent.com/u/445529...,,https://api.github.com/users/LucasG0,https://github.com/LucasG0,https://api.github.com/users/LucasG0/followers,https://api.github.com/users/LucasG0/following...,https://api.github.com/users/LucasG0/gists{/gi...,https://api.github.com/users/LucasG0/starred{/...,https://api.github.com/users/LucasG0/subscript...,https://api.github.com/users/LucasG0/orgs,https://api.github.com/users/LucasG0/repos,https://api.github.com/users/LucasG0/events{/p...,https://api.github.com/users/LucasG0/received_...,User,False
12,eromoe,3938751,MDQ6VXNlcjM5Mzg3NTE=,https://avatars.githubusercontent.com/u/393875...,,https://api.github.com/users/eromoe,https://github.com/eromoe,https://api.github.com/users/eromoe/followers,https://api.github.com/users/eromoe/following{...,https://api.github.com/users/eromoe/gists{/gis...,https://api.github.com/users/eromoe/starred{/o...,https://api.github.com/users/eromoe/subscriptions,https://api.github.com/users/eromoe/orgs,https://api.github.com/users/eromoe/repos,https://api.github.com/users/eromoe/events{/pr...,https://api.github.com/users/eromoe/received_e...,User,False
13,datapythonista,10058240,MDQ6VXNlcjEwMDU4MjQw,https://avatars.githubusercontent.com/u/100582...,,https://api.github.com/users/datapythonista,https://github.com/datapythonista,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/gi...,https://api.github.com/users/datapythonista/st...,https://api.github.com/users/datapythonista/su...,https://api.github.com/users/datapythonista/orgs,https://api.github.com/users/datapythonista/repos,https://api.github.com/users/datapythonista/ev...,https://api.github.com/users/datapythonista/re...,User,False
14,lorentzbao,19342156,MDQ6VXNlcjE5MzQyMTU2,https://avatars.githubusercontent.com/u/193421...,,https://api.github.com/users/lorentzbao,https://github.com/lorentzbao,https://api.github.com/users/lorentzbao/followers,https://api.github.com/users/lorentzbao/follow...,https://api.github.com/users/lorentzbao/gists{...,https://api.github.com/users/lorentzbao/starre...,https://api.github.com/users/lorentzbao/subscr...,https://api.github.com/users/lorentzbao/orgs,https://api.github.com/users/lorentzbao/repos,https://api.github.com/users/lorentzbao/events...,https://api.github.com/users/lorentzbao/receiv...,User,False
15,ehariri,21693509,MDQ6VXNlcjIxNjkzNTA5,https://avatars.githubusercontent.com/u/216935...,,https://api.github.com/users/ehariri,https://github.com/ehariri,https://api.github.com/users/ehariri/followers,https://api.github.com/users/ehariri/following...,https://api.github.com/users/ehariri/gists{/gi...,https://api.github.com/users/ehariri/starred{/...,https://api.github.com/users/ehariri/subscript...,https://api.github.com/users/ehariri/orgs,https://api.github.com/users/ehariri/repos,https://api.github.com/users/ehariri/events{/p...,https://api.github.com/users/ehariri/received_...,User,False
16,mosc9575,68053396,MDQ6VXNlcjY4MDUzMzk2,https://avatars.githubusercontent.com/u/680533...,,https://api.github.com/users/mosc9575,https://github.com/mosc9575,https://api.github.com/users/mosc9575/followers,https://api.github.com/users/mosc9575/followin...,https://api.github.com/users/mosc9575/gists{/g...,https://api.github.com/users/mosc9575/starred{...,https://api.github.com/users/mosc9575/subscrip...,https://api.github.com/users/mosc9575/orgs,https://api.github.com/users/mosc9575/repos,https://api.github.com/users/mosc9575/events{/...,https://api.github.com/users/mosc9575/received...,User,False
17,shyamsantoki,56479219,MDQ6VXNlcjU2NDc5MjE5,https://avatars.githubusercontent.com/u/564792...,,https://api.github.com/users/shyamsantoki,https://github.com/shyamsantoki,https://api.github.com/users/shyamsantoki/foll...,https://api.github.com/users/shyamsantoki/foll...,https://api.github.com/users/shyamsantoki/gist...,https://api.github.com/users/shyamsantoki/star...,https://api.github.com/users/shyamsantoki/subs...,https://api.github.com/users/shyamsantoki/orgs,https://api.github.com/users/shyamsantoki/repos,https://api.github.com/users/shyamsantoki/even...,https://api.github.com/users/shyamsantoki/rece...,User,False
18,twoertwein,6618166,MDQ6VXNlcjY2MTgxNjY=,https://avatars.githubusercontent.com/u/661816...,,https://api.github.com/users/twoertwein,https://github.com/twoertwein,https://api.github.com/users/twoertwein/followers,https://api.github.com/users/twoertwein/follow...,https://api.github.com/users/twoertwein/gists{...,https://api.github.com/users/twoertwein/starre...,https://api.github.com/users/twoertwein/subscr...,https://api.github.com/users/twoertwein/orgs,https://api.github.com/users/twoertwein/repos,https://api.github.com/users/twoertwein/events...,https://api.github.com/users/twoertwein/receiv...,User,False
19,vruthik,59946643,MDQ6VXNlcjU5OTQ2NjQz,https://avatars.githubusercontent.com/u/599466...,,https://api.github.com/users/vruthik,https://github.com/vruthik,https://api.github.com/users/vruthik/followers,https://api.github.com/users/vruthik/following...,https://api.github.com/users/vruthik/gists{/gi...,https://api.github.com/users/vruthik/starred{/...,https://api.github.com/users/vruthik/subscript...,https://api.github.com/users/vruthik/orgs,https://api.github.com/users/vruthik/repos,https://api.github.com/users/vruthik/events{/p...,https://api.github.com/users/vruthik/received_...,User,False
20,charlesbluca,20627856,MDQ6VXNlcjIwNjI3ODU2,https://avatars.githubusercontent.com/u/206278...,,https://api.github.com/users/charlesbluca,https://github.com/charlesbluca,https://api.github.com/users/charlesbluca/foll...,https://api.github.com/users/charlesbluca/foll...,https://api.github.com/users/charlesbluca/gist...,https://api.github.com/users/charlesbluca/star...,https://api.github.com/users/charlesbluca/subs...,https://api.github.com/users/charlesbluca/orgs,https://api.github.com/users/charlesbluca/repos,https://api.github.com/users/charlesbluca/even...,https://api.github.com/users/charlesbluca/rece...,User,False
21,andjhall,77794567,MDQ6VXNlcjc3Nzk0NTY3,https://avatars.githubusercontent.com/u/777945...,,https://api.github.com/users/andjhall,https://github.com/andjhall,https://api.github.com/users/andjhall/followers,https://api.github.com/users/andjhall/followin...,https://api.github.com/users/andjhall/gists{/g...,https://api.github.com/users/andjhall/starred{...,https://api.github.com/users/andjhall/subscrip...,https://api.github.com/users/andjhall/orgs,https://api.github.com/users/andjhall/repos,https://api.github.com/users/andjhall/events{/...,https://api.github.com/users/andjhall/received...,User,False
22,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
23,mroeschke,10647082,MDQ6VXNlcjEwNjQ3MDgy,https://avatars.githubusercontent.com/u/106470...,,https://api.github.com/users/mroeschke,https://github.com/mroeschke,https://api.github.com/users/mroeschke/followers,https://api.github.com/users/mroeschke/followi...,https://api.github.com/users/mroeschke/gists{/...,https://api.github.com/users/mroeschke/starred...,https://api.github.com/users/mroeschke/subscri...,https://api.github.com/users/mroeschke/orgs,https://api.github.com/users/mroeschke/repos,https://api.github.com/users/mroeschke/events{...,https://api.github.com/users/mroeschke/receive...,User,False
24,ma3da,34522496,MDQ6VXNlcjM0NTIyNDk2,https://avatars.githubusercontent.com/u/345224...,,https://api.github.com/users/ma3da,https://github.com/ma3da,https://api.github.com/users/ma3da/followers,https://api.github.com/users/ma3da/following{/...,https://api.github.com/users/ma3da/gists{/gist...,https://api.github.com/users/ma3da/starred{/ow...,https://api.github.com/users/ma3da/subscriptions,https://api.github.com/users/ma3da/orgs,https://api.github.com/users/ma3da/repos,https://api.github.com/users/ma3da/events{/pri...,https://api.github.com/users/ma3da/received_ev...,User,False
25,kwhkim,4476168,MDQ6VXNlcjQ0NzYxNjg=,https://avatars.githubusercontent.com/u/447616...,,https://api.github.com/users/kwhkim,https://github.com/kwhkim,https://api.github.com/users/kwhkim/followers,https://api.github.com/users/kwhkim/following{...,https://api.github.com/users/kwhkim/gists{/gis...,https://api.github.com/users/kwhkim/starred{/o...,https://api.github.com/users/kwhkim/subscriptions,https://api.github.com/users/kwhkim/orgs,https://api.github.com/users/kwhkim/repos,https://api.github.com/users/kwhkim/events{/pr...,https://api.github.com/users/kwhkim/received_e...,User,False
26,galipremsagar,11664259,MDQ6VXNlcjExNjY0MjU5,https://avatars.githubusercontent.com/u/116642...,,https://api.github.com/users/galipremsagar,https://github.com/galipremsagar,https://api.github.com/users/galipremsagar/fol...,https://api.github.com/users/galipremsagar/fol...,https://api.github.com/users/galipremsagar/gis...,https://api.github.com/users/galipremsagar/sta...,https://api.github.com/users/galipremsagar/sub...,https://api.github.com/users/galipremsagar/orgs,https://api.github.com/users/galipremsagar/repos,https://api.github.com/users/galipremsagar/eve...,https://api.github.com/users/galipremsagar/rec...,User,False
27,Dr-Irv,15113894,MDQ6VXNlcjE1MTEzODk0,https://avatars.githubusercontent.com/u/151138...,,https://api.github.com/users/Dr-Irv,https://github.com/Dr-Irv,https://api.github.com/users/Dr-Irv/followers,https://api.github.com/users/Dr-Irv/following{...,https://api.github.com/users/Dr-Irv/gists{/gis...,https://api.github.com/users/Dr-Irv/starred{/o...,https://api.github.com/users/Dr-Irv/subscriptions,https://api.github.com/users/Dr-Irv/orgs,https://api.github.com/users/Dr-Irv/repos,https://api.github.com/users/Dr-Irv/events{/pr...,https://api.github.com/users/Dr-Irv/received_e...,User,False
28,Moisan,31669,MDQ6VXNlcjMxNjY5,https://avatars.githubusercontent.com/u/31669?v=4,,https://api.github.com/users/Moisan,https://github.com/Moisan,https://api.github.com/users/Moisan/followers,https://api.github.com/users/Moisan/following{...,https://api.github.com/users/Moisan/gists{/gis...,https://api.github.com/users/Moisan/starred{/o...,https://api.github.com/users/Moisan/subscriptions,https://api.github.com/users/Moisan/orgs,https://api.github.com/users/Moisan/repos,https://api.github.com/users/Moisan/events{/pr...,https://api.github.com/users/Moisan/received_e...,User,False
29,maalgorium,18078278,MDQ6VXNlcjE4MDc4Mjc4,https://avatars.githubusercontent.com/u/180782...,,https://api.github.com/users/maalgorium,https://github.com/maalgorium,https://api.github.com/users/maalgorium/followers,https://api.github.com/users/maalgorium/follow...,https://api.github.com/users/maalgorium/gists{...,https://api.github.com/users/maalgorium/starre...,https://api.github.com/users/maalgorium/subscr...,https://api.github.com/users/maalgorium/orgs,https://api.github.com/users/maalgorium/repos,https://api.github.com/users/maalgorium/events...,https://api.github.com/users/maalgorium/receiv...,User,False

In [55]:
df5

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46811,1209936718,PR_kwDOAA0YD842gR6J,46811,BUG: parsing nanoseconds incorrect resolution,...,2022-04-20 16:39:19+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46810,1209664145,I_kwDOAA0YD85IGgKR,46810,BUG: `pd.read_excel` writing numbers with .0 i...,...,2022-04-20 15:04:39+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46809,1209401729,I_kwDOAA0YD85IFgGB,46809,ENH: allow functions in `keep` parameter of `d...,...,2022-04-20 13:20:45+00:00,NaT,NONE,NaN,NaN,NaN,#### Is your feature request related to a prob...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46808,1209226761,I_kwDOAA0YD85IE1YJ,46808,BUG: TimeStamp index rolling problems,...,2022-04-20 06:35:44+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46807,1208928430,I_kwDOAA0YD85IDsiu,46807,BUG: Inconsistent result of in-place Series.re...,...,2022-04-19 22:39:14+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46806,1208857290,PR_kwDOAA0YD842c2yI,46806,DOC: building page for nested methods doesn't ...,...,2022-04-20 07:22:16+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,closes #46804 \r\n\r\nLike this\r\n```\r\n pyt...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46804,1208841558,I_kwDOAA0YD85IDXVW,46804,DOC: building page for nested methods doesn't ...,...,2022-04-19 20:43:26+00:00,NaT,MEMBER,NaN,NaN,NaN,The following\r\n```\r\npython make.py --singl...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46803,1208773182,PR_kwDOAA0YD842ck7I,46803,REF: re-use Localizer for tz_convert_from_utc,...,2022-04-19 19:26:36+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Also de-duplicate `tdata` construction and avo...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46802,1208577321,PR_kwDOAA0YD842b-lJ,46802,ENH: adding datetime default output formatting...,...,2022-04-19 16:12:59+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] partly addresses #46755\r\n- [x] [Tests ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46800,1208305496,I_kwDOAA0YD85IBUdY,46800,BUG: df.eval with inplace behavior changes aft...,...,2022-04-19 12:40:34+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46799,1207499980,I_kwDOAA0YD85H-PzM,46799,BUG: Merge fails on nullable integer columns w...,...,2022-04-19 23:35:43+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46798,1207172802,PR_kwDOAA0YD842Xj3P,46798,BUG: `DataFrameGroupBy.value_counts` includes ...,...,2022-04-18 21:11:22+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46357\r\n- [X] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46797,1206612518,I_kwDOAA0YD85H63Im,46797,BUG: pandas.cut doesnt respect to `precision...,...,2022-04-18 03:20:23+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46793,1206370745,I_kwDOAA0YD85H58G5,46793,WEB: Use mambaforge for the getting started in...,...,2022-04-17 13:07:21+00:00,NaT,MEMBER,NaN,NaN,NaN,We've got [this page](https://pandas.pydata.or...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46792,1206301209,PR_kwDOAA0YD842Uu8E,46792,ENH: Add numeric_only to resampler methods,...,2022-04-19 14:51:52+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #46442 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46791,1206170540,PR_kwDOAA0YD842UW62,46791,Change `mylen` function to account for NaN emp...,...,2022-04-19 03:06:01+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46084 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46790,1206164359,I_kwDOAA0YD85H5JuH,46790,ENH: Add option for `bold_column_headers` to `...,...,2022-04-18 07:21:23+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,In the latest pandas version 1.4.2 there exist...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46789,1206141718,PR_kwDOAA0YD842UTSU,46789,BUG: .fillna(-1) does not work in pd.eval,...,2022-04-17 17:16:14+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Adding ```self.value``` resolves the issue #46...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46786,1205872267,PR_kwDOAA0YD842TiuU,46786,TYP: CallableDynamicDoc,...,2022-04-15 20:35:48+00:00,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,The more tricky parts of #46698.\r\n\r\nAdding...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46784,1205765682,PR_kwDOAA0YD842TO4h,46784,ENH: Added Index param to to_dict like in to_j...,...,2022-04-20 01:54:55+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46398 \r\n- [X] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46783,1205740295,I_kwDOAA0YD85H3iMH,46783,BUG: `dropna=False` not respected for groupby ...,...,2022-04-15 21:57:07+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46778,1204912401,PR_kwDOAA0YD842QdlT,46778,BUG: fixed buggy behavior in pivot_table with ...,...,2022-04-18 17:27:13+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #26568(Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46776,1204378879,I_kwDOAA0YD85HyVz_,46776,RLS: 2.0,...,2022-04-15 17:13:17+00:00,NaT,MEMBER,NaN,NaN,NaN,Tracking issue for the 2.0 release. (Note: pan...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46774,1204039393,PR_kwDOAA0YD842NvHH,46774,ENH: Create ArrowDtype,...,2022-04-18 22:27:49+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] All [code checks passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46771,1203768268,PR_kwDOAA0YD842M2rW,46771,BUG: date_range not excluding dates correctly ...,...,2022-04-18 11:55:04+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46331 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46770,1203632158,I_kwDOAA0YD85Hvfge,46770,"BUG: `CategoricalDtype(None, False)` does not ...",...,2022-04-14 11:24:46+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46769,1203606102,I_kwDOAA0YD85HvZJW,46769,BUG: Pandas Index fails with `bitwise` ufuncs,...,2022-04-14 10:31:20+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46768,1203529564,I_kwDOAA0YD85HvGdc,46768,"DEPR: Deprecate daysinmonth, dayofweek, dayofyear",...,2022-04-14 11:16:55+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,Based on original issue #1723 and https://gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46766,1203443826,PR_kwDOAA0YD842LxwD,46766,DOC: add examples to groupby.first,...,2022-04-18 17:52:00+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46765,1203409750,I_kwDOAA0YD85HupNW,46765,BUG: unable to read sftp urls despite fsspec s...,...,2022-04-13 20:04:59+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN

In [56]:
df5.to_pickle("my_picle_file")

In [57]:
h5_data=pd.HDFStore('test12.h5')

In [58]:
h5_data['obj1']=df5

C:\Users\Amit Kumar Singh\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block6_values] [items->Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'node_id', 'title', 'user', 'labels', 'state', 'assignee',
       'assignees', 'milestone', 'author_association', 'pull_request', 'body',
       'reactions', 'timeline_url'],
      dtype='object')]

  exec(code_obj, self.user_global_ns, self.user_ns)

In [59]:
h5_data['obj1']

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46811,1209936718,PR_kwDOAA0YD842gR6J,46811,BUG: parsing nanoseconds incorrect resolution,...,2022-04-20 16:39:19+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46810,1209664145,I_kwDOAA0YD85IGgKR,46810,BUG: `pd.read_excel` writing numbers with .0 i...,...,2022-04-20 15:04:39+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46809,1209401729,I_kwDOAA0YD85IFgGB,46809,ENH: allow functions in `keep` parameter of `d...,...,2022-04-20 13:20:45+00:00,NaT,NONE,NaN,NaN,NaN,#### Is your feature request related to a prob...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46808,1209226761,I_kwDOAA0YD85IE1YJ,46808,BUG: TimeStamp index rolling problems,...,2022-04-20 06:35:44+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46807,1208928430,I_kwDOAA0YD85IDsiu,46807,BUG: Inconsistent result of in-place Series.re...,...,2022-04-19 22:39:14+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46806,1208857290,PR_kwDOAA0YD842c2yI,46806,DOC: building page for nested methods doesn't ...,...,2022-04-20 07:22:16+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,closes #46804 \r\n\r\nLike this\r\n```\r\n pyt...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46804,1208841558,I_kwDOAA0YD85IDXVW,46804,DOC: building page for nested methods doesn't ...,...,2022-04-19 20:43:26+00:00,NaT,MEMBER,NaN,NaN,NaN,The following\r\n```\r\npython make.py --singl...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46803,1208773182,PR_kwDOAA0YD842ck7I,46803,REF: re-use Localizer for tz_convert_from_utc,...,2022-04-19 19:26:36+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Also de-duplicate `tdata` construction and avo...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46802,1208577321,PR_kwDOAA0YD842b-lJ,46802,ENH: adding datetime default output formatting...,...,2022-04-19 16:12:59+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] partly addresses #46755\r\n- [x] [Tests ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46800,1208305496,I_kwDOAA0YD85IBUdY,46800,BUG: df.eval with inplace behavior changes aft...,...,2022-04-19 12:40:34+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46799,1207499980,I_kwDOAA0YD85H-PzM,46799,BUG: Merge fails on nullable integer columns w...,...,2022-04-19 23:35:43+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46798,1207172802,PR_kwDOAA0YD842Xj3P,46798,BUG: `DataFrameGroupBy.value_counts` includes ...,...,2022-04-18 21:11:22+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46357\r\n- [X] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46797,1206612518,I_kwDOAA0YD85H63Im,46797,BUG: pandas.cut doesnt respect to `precision...,...,2022-04-18 03:20:23+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46793,1206370745,I_kwDOAA0YD85H58G5,46793,WEB: Use mambaforge for the getting started in...,...,2022-04-17 13:07:21+00:00,NaT,MEMBER,NaN,NaN,NaN,We've got [this page](https://pandas.pydata.or...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46792,1206301209,PR_kwDOAA0YD842Uu8E,46792,ENH: Add numeric_only to resampler methods,...,2022-04-19 14:51:52+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #46442 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46791,1206170540,PR_kwDOAA0YD842UW62,46791,Change `mylen` function to account for NaN emp...,...,2022-04-19 03:06:01+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46084 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46790,1206164359,I_kwDOAA0YD85H5JuH,46790,ENH: Add option for `bold_column_headers` to `...,...,2022-04-18 07:21:23+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,In the latest pandas version 1.4.2 there exist...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46789,1206141718,PR_kwDOAA0YD842UTSU,46789,BUG: .fillna(-1) does not work in pd.eval,...,2022-04-17 17:16:14+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Adding ```self.value``` resolves the issue #46...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46786,1205872267,PR_kwDOAA0YD842TiuU,46786,TYP: CallableDynamicDoc,...,2022-04-15 20:35:48+00:00,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,The more tricky parts of #46698.\r\n\r\nAdding...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46784,1205765682,PR_kwDOAA0YD842TO4h,46784,ENH: Added Index param to to_dict like in to_j...,...,2022-04-20 01:54:55+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46398 \r\n- [X] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46783,1205740295,I_kwDOAA0YD85H3iMH,46783,BUG: `dropna=False` not respected for groupby ...,...,2022-04-15 21:57:07+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46778,1204912401,PR_kwDOAA0YD842QdlT,46778,BUG: fixed buggy behavior in pivot_table with ...,...,2022-04-18 17:27:13+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #26568(Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46776,1204378879,I_kwDOAA0YD85HyVz_,46776,RLS: 2.0,...,2022-04-15 17:13:17+00:00,NaT,MEMBER,NaN,NaN,NaN,Tracking issue for the 2.0 release. (Note: pan...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46774,1204039393,PR_kwDOAA0YD842NvHH,46774,ENH: Create ArrowDtype,...,2022-04-18 22:27:49+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] All [code checks passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46771,1203768268,PR_kwDOAA0YD842M2rW,46771,BUG: date_range not excluding dates correctly ...,...,2022-04-18 11:55:04+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46331 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46770,1203632158,I_kwDOAA0YD85Hvfge,46770,"BUG: `CategoricalDtype(None, False)` does not ...",...,2022-04-14 11:24:46+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46769,1203606102,I_kwDOAA0YD85HvZJW,46769,BUG: Pandas Index fails with `bitwise` ufuncs,...,2022-04-14 10:31:20+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46768,1203529564,I_kwDOAA0YD85HvGdc,46768,"DEPR: Deprecate daysinmonth, dayofweek, dayofyear",...,2022-04-14 11:16:55+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,Based on original issue #1723 and https://gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46766,1203443826,PR_kwDOAA0YD842LxwD,46766,DOC: add examples to groupby.first,...,2022-04-18 17:52:00+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46765,1203409750,I_kwDOAA0YD85HupNW,46765,BUG: unable to read sftp urls despite fsspec s...,...,2022-04-13 20:04:59+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN

In [60]:
h5_data.put('obj2',df,format='table')

In [61]:
h5_data.select('obj2',where =['index>10 and index<=12' ])

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
11,12,B Akhil,7-Oct-77,Right_Hand,Right-arm medium-fast,India,0,NaN
12,13,AA Noffke,30-Apr-77,Right_Hand,Right-arm fast-medium,Australia,0,NaN

In [62]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [63]:
df[df.dtypes[df.dtypes=='object'].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [64]:
df[df.dtypes[df.dtypes=='object'].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [65]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [66]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [67]:
df[df.dtypes[df.dtypes=='float64'].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [68]:
df['amit']=df['PassengerId']

In [69]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,amit
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,887
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,888
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,889
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,890
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,891

In [70]:
pd.Categorical(df['Sex'])

['male', 'female', 'female', 'female', 'male', ..., 'male', 'female', 'female', 'male', 'male']
Length: 891
Categories (2, object): ['female', 'male']

In [71]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [72]:
df['Cabin'].isnull()==False

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: Cabin, Length: 891, dtype: bool

In [73]:
ser=df['Cabin'][df['Cabin'].isnull()==False]

In [74]:
type(ser)

pandas.core.series.Series

In [75]:
len(ser.index)

204

In [76]:
df.iloc[ser.index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,amit
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,7
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,11
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,872
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,873
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,880
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,888
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,890

In [77]:
df[['Fare']].max()

Fare    512.3292
dtype: float64

In [78]:
df[df['Fare']== max(df['Fare'])]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [79]:
max(df['Fare'])

512.3292

In [80]:
titanic_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [81]:
titanic_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [82]:
titanic_data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [83]:
titanic_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [84]:
titanic_data[titanic_data.dtypes[titanic_data.dtypes=='object'].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [85]:
titanic_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [86]:
titanic_data['Cabin'][titanic_data['Cabin'].isnull()==True]

0      NaN
2      NaN
4      NaN
5      NaN
7      NaN
      ...
884    NaN
885    NaN
886    NaN
888    NaN
890    NaN
Name: Cabin, Length: 687, dtype: object

In [87]:
cc=titanic_data[titanic_data['Fare']==min(titanic_data['Fare'])]

In [88]:
cc.count()

PassengerId    15
Survived       15
Pclass         15
Name           15
Sex            15
Age             7
SibSp          15
Parch          15
Ticket         15
Fare           15
Cabin           3
Embarked       15
dtype: int64

In [89]:
cc.index

Int64Index([179, 263, 271, 277, 302, 413, 466, 481, 597, 633, 674, 732, 806,
            815, 822],
           dtype='int64')

In [90]:
titanic_data.iloc[cc.index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,NaN,S
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,NaN,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S

In [91]:
dy=titanic_data.dtypes

In [92]:
dy

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [93]:
dy['Sex']

dtype('O')

In [94]:
type(dy)

pandas.core.series.Series

In [95]:
dy[0:10:2]

PassengerId     int64
Pclass          int64
Sex            object
SibSp           int64
Ticket         object
dtype: object

In [96]:
#titanic_data['Sex'][1]

In [97]:
list(titanic_data['Sex'])[0:100:10]

['male',
 'female',
 'male',
 'male',
 'female',
 'male',
 'male',
 'male',
 'male',
 'male']

In [98]:
list(titanic_data)[1]

'Survived'

In [99]:
titanic_data_cat=titanic_data[titanic_data.dtypes[titanic_data.dtypes=='object'].index]

In [100]:
titanic_data_cat.describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [101]:
import numpy as np

In [102]:
np.where(titanic_data['Age'].isnull()==True)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dtype=int64),)

In [103]:
titanic_data[titanic_data['Age'].isnull()==True]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [104]:
titanic_train_age_null=np.where(titanic_data['Age'].isnull()==True)

In [105]:
titanic_train_age_null

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dtype=int64),)

In [106]:
titanic_data.iloc[titanic_train_age_null]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [107]:
titanic_data.iloc[[2,7,12,19]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.225,NaN,C

In [108]:
np.where(titanic_data['Fare']==titanic_data['Fare'].max())

(array([258, 679, 737], dtype=int64),)

In [109]:
titanic_data.iloc[np.where(titanic_data['Fare']==titanic_data['Fare'].max())]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [110]:
titanic_data[titanic_data['Age']==24][['Name']]

                                                  Name
89                              Celotti, Mr. Francesco
118                           Baxter, Mr. Quigg Edmond
127                          Madsen, Mr. Fridtjof Arne
139                                 Giglio, Mr. Victor
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...
199             Yrois, Miss. Henriette ("Mrs Harbeck")
210                                     Ali, Mr. Ahmed
234                  Leyson, Mr. Robert William Norman
247                    Hamalainen, Mrs. William (Anna)
293                                Haas, Miss. Aloisia
294                                   Mineff, Mr. Ivan
310                     Hays, Miss. Margaret Bechstein
316                Kantor, Mrs. Sinai (Miriam Sternin)
341                     Fortune, Miss. Alice Elizabeth
345                      Brown, Miss. Amelia "Mildred"
369                      Aubart, Mme. Leontine Pauline
394  Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...
437              Richards, Mrs. Sidney (Emily Hocking)
499                                 Svensson, Mr. Olof
514                                  Coleff, Mr. Satio
565                               Davies, Mr. Alfred J
600  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...
615                                Herman, Miss. Alice
641                               Sagesser, Mlle. Emma
655                          Hickman, Mr. Leonard Mark
710   Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")
743                                  McNamee, Mr. Neal
770                             Lievens, Mr. Rene Aime
858              Baclini, Mrs. Solomon (Latifa Qurban)
864                             Gill, Mr. John William

In [111]:
titanic_data.iloc[np.where(titanic_data['Age']==24)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
89,90,0,3,"Celotti, Mr. Francesco",male,24.0,0,0,343275,8.0500,NaN,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
127,128,1,3,"Madsen, Mr. Fridtjof Arne",male,24.0,0,0,C 17369,7.1417,NaN,S
139,140,0,1,"Giglio, Mr. Victor",male,24.0,0,0,PC 17593,79.2000,B86,C
142,143,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...",female,24.0,1,0,STON/O2. 3101279,15.8500,NaN,S
199,200,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.0,0,0,248747,13.0000,NaN,S
210,211,0,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S
234,235,0,2,"Leyson, Mr. Robert William Norman",male,24.0,0,0,C.A. 29566,10.5000,NaN,S
247,248,1,2,"Hamalainen, Mrs. William (Anna)",female,24.0,0,2,250649,14.5000,NaN,S
293,294,0,3,"Haas, Miss. Aloisia",female,24.0,0,0,349236,8.8500,NaN,S
294,295,0,3,"Mineff, Mr. Ivan",male,24.0,0,0,349233,7.8958,NaN,S
310,311,1,1,"Hays, Miss. Margaret Bechstein",female,24.0,0,0,11767,83.1583,C54,C
316,317,1,2,"Kantor, Mrs. Sinai (Miriam Sternin)",female,24.0,1,0,244367,26.0000,NaN,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
345,346,1,2,"Brown, Miss. Amelia ""Mildred""",female,24.0,0,0,248733,13.0000,F33,S
369,370,1,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C
394,395,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.0,0,2,PP 9549,16.7000,G6,S
437,438,1,2,"Richards, Mrs. Sidney (Emily Hocking)",female,24.0,2,3,29106,18.7500,NaN,S
499,500,0,3,"Svensson, Mr. Olof",male,24.0,0,0,350035,7.7958,NaN,S
514,515,0,3,"Coleff, Mr. Satio",male,24.0,0,0,349209,7.4958,NaN,S
565,566,0,3,"Davies, Mr. Alfred J",male,24.0,2,0,A/4 48871,24.1500,NaN,S
600,601,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.0,2,1,243847,27.0000,NaN,S
615,616,1,2,"Herman, Miss. Alice",female,24.0,1,2,220845,65.0000,NaN,S
641,642,1,1,"Sagesser, Mlle. Emma",female,24.0,0,0,PC 17477,69.3000,B35,C
655,656,0,2,"Hickman, Mr. Leonard Mark",male,24.0,2,0,S.O.C. 14879,73.5000,NaN,S
710,711,1,1,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",female,24.0,0,0,PC 17482,49.5042,C90,C
743,744,0,3,"McNamee, Mr. Neal",male,24.0,1,0,376566,16.1000,NaN,S
770,771,0,3,"Lievens, Mr. Rene Aime",male,24.0,0,0,345781,9.5000,NaN,S
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,NaN,C
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S

In [112]:
titanic_data[titanic_data['Age']==titanic_data['Age'].min()]['Name']

803    Thomas, Master. Assad Alexander
Name: Name, dtype: object

In [113]:
titanic_data.iloc[np.where(titanic_data['Age'].min())]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [114]:
titanic_data.iloc[np.where(titanic_data['Age'].min())]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [115]:
titanic_data[['Age','Cabin']][titanic_data['Cabin'].isnull()==True]

      Age Cabin
0    22.0   NaN
2    26.0   NaN
4    35.0   NaN
5     NaN   NaN
7     2.0   NaN
..    ...   ...
884  25.0   NaN
885  39.0   NaN
886  27.0   NaN
888   NaN   NaN
890  32.0   NaN

[687 rows x 2 columns]

In [116]:
titanic_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [117]:
titanic_data['Name'][(titanic_data.Survived==1) & (titanic_data.Sex=='male')]

17        Williams, Mr. Charles Eugene
21               Beesley, Mr. Lawrence
23        Sloper, Mr. William Thompson
36                    Mamee, Mr. Hanna
55                   Woolner, Mr. Hugh
                    ...
838                    Chip, Mr. Chang
839               Marechal, Mr. Pierre
857             Daly, Mr. Peter Denis
869    Johnson, Master. Harold Theodor
889              Behr, Mr. Karl Howell
Name: Name, Length: 109, dtype: object

In [118]:
titanic_data.Name[(titanic_data.Survived==1) & (titanic_data.Sex=='male')]

17        Williams, Mr. Charles Eugene
21               Beesley, Mr. Lawrence
23        Sloper, Mr. William Thompson
36                    Mamee, Mr. Hanna
55                   Woolner, Mr. Hugh
                    ...
838                    Chip, Mr. Chang
839               Marechal, Mr. Pierre
857             Daly, Mr. Peter Denis
869    Johnson, Master. Harold Theodor
889              Behr, Mr. Karl Howell
Name: Name, Length: 109, dtype: object

In [119]:
titanic_data['max_fare']=int(titanic_data.Fare.max())

In [120]:
titanic_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,max_fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,512
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,512
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,512
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,512
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,512
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,512
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,512
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,512
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,512
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,512

In [121]:
l=[1,2,3,4,5]

In [122]:
pd.Series(l)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [123]:
d = {'key' : "sudh" , "title" :"kumar" , "mail_id" : "sudha@gmail.com"}

In [124]:
pd.DataFrame(d,index=['a','b','c'])

    key  title          mail_id
a  sudh  kumar  sudha@gmail.com
b  sudh  kumar  sudha@gmail.com
c  sudh  kumar  sudha@gmail.com

In [125]:
pd.Series(d)

key                   sudh
title                kumar
mail_id    sudha@gmail.com
dtype: object

In [126]:
pd.DataFrame(pd.Series(d))

                       0
key                 sudh
title              kumar
mail_id  sudha@gmail.com

In [127]:
np.random.randn(3)

array([-1.70771275, -0.36692078,  1.05765072])

In [128]:
np.random.randn(2,3)

array([[ 0.46831021, -0.76819043,  0.47218301],
       [ 0.3802759 , -0.19526522, -2.13931922]])

In [129]:
np.random.randn(2,2,3)

array([[[-1.09289951, -1.66401777,  1.29804896],
        [-0.4181993 ,  0.71543911, -0.02926703]],

       [[ 1.09772323, -0.25164876,  0.58331793],
        [-1.29538796,  1.55874591,  0.29605249]]])

In [130]:
arr=np.random.randn(2,2)

In [131]:
pd.DataFrame(arr)

          0         1
0  0.909875 -0.191200
1 -0.258653  0.251488

In [132]:
pd.Series(np.array([1,2,3]),index=['a','b','c'])

a    1
b    2
c    3
dtype: int32

In [133]:
ser = pd.Series(np.array([4,5,6,7,8]),index=['a',22,'sudh',"kumar",'c'])

In [134]:
ser

a        4
22       5
sudh     6
kumar    7
c        8
dtype: int32

In [135]:
ser.iloc[0]

4

In [136]:
ser.loc['sudh']

6

In [137]:
np.random.randint(1,4,(4,2))

array([[3, 2],
       [2, 3],
       [3, 3],
       [3, 1]])

In [138]:
t=(1,2,1,2,1)

In [139]:
type(t)

tuple

In [140]:
t

(1, 2, 1, 2, 1)

In [141]:
t.count(1)

3

In [142]:
s={1,2,3,4,1}

In [143]:
type(s)

set

In [144]:
s

{1, 2, 3, 4}

In [145]:
s.add(5)

In [146]:
l=[1,2,'a','dd',3.3]

In [147]:
l

[1, 2, 'a', 'dd', 3.3]

In [148]:
l=['amit']

In [149]:
l

['amit']

In [150]:
l.append('shweta')

In [151]:
p='amit'

In [152]:
l.append(p)

In [153]:
person={"name":"amit","sex":"M","comp":[1,2,3]}

In [154]:
for a,b in person.items():
    print(a,'     :        ',b)

name      :         amit
sex      :         M
comp      :         [1, 2, 3]

In [155]:
"name" in person

True

In [156]:
if "name" in person:
    print('yes')
    person["name"]='Shweta'

yes

In [157]:
person

{'name': 'Shweta', 'sex': 'M', 'comp': [1, 2, 3]}

In [158]:
'M' in person

False

In [159]:
#person["M"]

In [160]:
'sex' in person

True

In [161]:
a=pd.DataFrame(np.random.randint(3,6,(3,4)),index=['a','b','c'],columns=['aa','bb','cc','dd'])

In [162]:
a.loc[['a'],['bb']]

   bb
a   3

In [163]:
a.iloc[1]

aa    4
bb    4
cc    3
dd    3
Name: b, dtype: int32

In [164]:
a

   aa  bb  cc  dd
a   3   3   5   3
b   4   4   3   3
c   5   3   4   5

In [165]:
a.iloc[[1,2],[1,3]]

   bb  dd
b   4   3
c   3   5

In [166]:
a.iloc[1:,3:3]

Empty DataFrame
Columns: []
Index: [b, c]

In [167]:
a.iloc[1:]

   aa  bb  cc  dd
b   4   4   3   3
c   5   3   4   5

In [168]:
a['new_col']=a.aa+a.dd

In [169]:
a

   aa  bb  cc  dd  new_col
a   3   3   5   3        6
b   4   4   3   3        7
c   5   3   4   5       10

In [170]:
a.drop('aa',axis=1,inplace=True)

In [171]:
a

   bb  cc  dd  new_col
a   3   5   3        6
b   4   3   3        7
c   3   4   5       10

In [172]:
a.drop('a',inplace=True)

In [173]:
a

   bb  cc  dd  new_col
b   4   3   3        7
c   3   4   5       10

In [174]:
np.random.seed(2)
df = pd.DataFrame(np.random.randn(4,5),index=['a','b','c','d'],columns=['x','y','z','u','v'])

In [175]:
df[df<0]

          x         y         z         u         v
a -0.416758 -0.056267 -2.136196       NaN -1.793436
b -0.841747       NaN -1.245288 -1.057952 -0.909008
c       NaN       NaN       NaN -1.117925       NaN
d -0.596160 -0.019130       NaN -0.747871       NaN

In [176]:
df.values[df.values<0]

array([-0.41675785, -0.05626683, -2.1361961 , -1.79343559, -0.84174737,
       -1.24528809, -1.05795222, -0.90900761, -1.11792545, -0.5961597 ,
       -0.0191305 , -0.74787095])

In [177]:
df.values[df.iloc[0:5]<0]

array([-0.41675785, -0.05626683, -2.1361961 , -1.79343559, -0.84174737,
       -1.24528809, -1.05795222, -0.90900761, -1.11792545, -0.5961597 ,
       -0.0191305 , -0.74787095])

In [178]:
df.iloc[0:5]<0

       x      y      z      u      v
a   True   True   True  False   True
b   True  False   True   True   True
c  False  False  False   True  False
d   True   True  False   True  False

In [179]:

c = df.values[df.values<0]
for i in df.columns:
    for j in df.index:
        if df.loc[j,i] in c:
            print(i,j)

x a
x b
x d
y a
y d
z a
z b
u b
u c
u d
v a
v b

In [180]:
df.columns

Index(['x', 'y', 'z', 'u', 'v'], dtype='object')

In [181]:
df.values

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081, -1.79343559],
       [-0.84174737,  0.50288142, -1.24528809, -1.05795222, -0.90900761],
       [ 0.55145404,  2.29220801,  0.04153939, -1.11792545,  0.53905832],
       [-0.5961597 , -0.0191305 ,  1.17500122, -0.74787095,  0.00902525]])

In [182]:
type(np.array([1,2,3,'Amit',4+8j]))

numpy.ndarray

In [183]:
np.array([1,2,3,'Amit',4+8j])

array(['1', '2', '3', 'Amit', '(4+8j)'], dtype='<U64')

In [184]:
np.array([[1,2],[2,3],[4,5,6]])

C:\Users\AMITKU~1\AppData\Local\Temp/ipykernel_20700/2670448388.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2],[2,3],[4,5,6]])

array([list([1, 2]), list([2, 3]), list([4, 5, 6])], dtype=object)

In [185]:
np.array([[[1,2],[2,3]],[[4,5],[2,3]]])

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [2, 3]]])

In [186]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [187]:
arr=np.array([[(1,2),(3,4)]])

In [188]:
mat=np.matrix(arr)

In [189]:
l=[1,2,3,4]

In [190]:
np.array(l)

array([1, 2, 3, 4])

In [191]:
np.asarray(l)

array([1, 2, 3, 4])

In [192]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [193]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [194]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [195]:
issubclass(np.matrix,np.ndarray)

True

In [196]:
#arr[-2]

In [197]:
arr=np.array([[(1,2,3),(3,4,3),(5,6,3),(7,8,3)],[(1,2,3),(3,4,3),(5,6,3),(7,8,9)]])

In [198]:
arr

array([[[1, 2, 3],
        [3, 4, 3],
        [5, 6, 3],
        [7, 8, 3]],

       [[1, 2, 3],
        [3, 4, 3],
        [5, 6, 3],
        [7, 8, 9]]])

In [199]:
arr[0:2]

array([[[1, 2, 3],
        [3, 4, 3],
        [5, 6, 3],
        [7, 8, 3]],

       [[1, 2, 3],
        [3, 4, 3],
        [5, 6, 3],
        [7, 8, 9]]])

In [200]:
for i in arr:
    print(i)

[[1 2 3]
 [3 4 3]
 [5 6 3]
 [7 8 3]]
[[1 2 3]
 [3 4 3]
 [5 6 3]
 [7 8 9]]

In [201]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [202]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [203]:
def even(x):
  for i in range(1,8):
       yield i



for i in even(2):
    print(i)

1
2
3
4
5
6
7

In [204]:
next(even)
next(even)
next(even)

TypeError: 'function' object is not an iterator

In [207]:
np.fromiter(range(3),dtype=int)

array([0, 1, 2])

In [210]:
arr

array([[[1, 2, 3],
        [3, 4, 3],
        [5, 6, 3],
        [7, 8, 3]],

       [[1, 2, 3],
        [3, 4, 3],
        [5, 6, 3],
        [7, 8, 9]]])

In [211]:
arr.ndim

3

In [212]:
arr.size

24

In [213]:
arr.shape

(2, 4, 3)

In [218]:
list(range(5))

[0, 1, 2, 3, 4]

In [220]:
np.arange(2.2)

array([0., 1., 2.])

In [221]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

In [227]:
list(range(9,4,-1))

[9, 8, 7, 6, 5]

AttributeError: module 'numpy' has no attribute 'linespace'

In [234]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [235]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [236]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [237]:
np.zeros((2,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [240]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [243]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [253]:
np.linspace([2,3],4,4,axis=1)

array([[2.        , 2.66666667, 3.33333333, 4.        ],
       [3.        , 3.33333333, 3.66666667, 4.        ]])

In [256]:
np.logspace([2,3],5)

array([[   100.        ,   1000.        ],
       [   115.13953993,   1098.54114199],
       [   132.57113656,   1206.79264064],
       [   152.64179672,   1325.71136559],
       [   175.75106249,   1456.3484775 ],
       [   202.35896477,   1599.85871961],
       [   232.99518105,   1757.51062485],
       [   268.26957953,   1930.69772888],
       [   308.88435965,   2120.95088792],
       [   355.64803062,   2329.95181052],
       [   409.49150624,   2559.5479227 ],
       [   471.48663635,   2811.76869797],
       [   542.86754393,   3088.84359648],
       [   625.05519253,   3393.2217719 ],
       [   719.685673  ,   3727.59372031],
       [   828.64277285,   4094.91506238],
       [   954.09547635,   4498.43266897],
       [  1098.54114199,   4941.71336132],
       [  1264.85521686,   5428.67543932],
       [  1456.3484775 ,   5963.62331659],
       [  1676.83293681,   6551.2855686 ],
       [  1930.69772888,   7196.85673001],
       [  2222.99648253,   7906.04321091],
       [  2559.5479227 ,   8685.11373751],
       [  2947.05170255,   9540.9547635 ],
       [  3393.2217719 ,  10481.13134155],
       [  3906.93993705,  11513.95399326],
       [  4498.43266897,  12648.55216855],
       [  5179.47467923,  13894.95494373],
       [  5963.62331659,  15264.17967175],
       [  6866.48845004,  16768.32936811],
       [  7906.04321091,  18420.69969327],
       [  9102.98177992,  20235.89647725],
       [ 10481.13134155,  22229.96482526],
       [ 12067.92640639,  24420.53094549],
       [ 13894.95494373,  26826.9579528 ],
       [ 15998.58719606,  29470.51702552],
       [ 18420.69969327,  32374.57542818],
       [ 21209.5088792 ,  35564.80306223],
       [ 24420.53094549,  39069.39937055],
       [ 28117.68697974,  42919.34260129],
       [ 32374.57542818,  47148.66363457],
       [ 37275.93720315,  51794.74679231],
       [ 42919.34260129,  56898.66029018],
       [ 49417.13361324,  62505.51925274],
       [ 56898.66029018,  68664.88450043],
       [ 65512.85568596,  75431.20063355],
       [ 75431.20063355,  82864.27728547],
       [ 86851.13737514,  91029.81779915],
       [100000.        , 100000.        ]])

In [259]:
a=np.linspace([1,6],40)

In [260]:
a.ndim

2

In [261]:
a.shape

(50, 2)

In [265]:
a.reshape(2,2,25)

array([[[ 1.        ,  6.        ,  1.79591837,  6.69387755,
          2.59183673,  7.3877551 ,  3.3877551 ,  8.08163265,
          4.18367347,  8.7755102 ,  4.97959184,  9.46938776,
          5.7755102 , 10.16326531,  6.57142857, 10.85714286,
          7.36734694, 11.55102041,  8.16326531, 12.24489796,
          8.95918367, 12.93877551,  9.75510204, 13.63265306,
         10.55102041],
        [14.32653061, 11.34693878, 15.02040816, 12.14285714,
         15.71428571, 12.93877551, 16.40816327, 13.73469388,
         17.10204082, 14.53061224, 17.79591837, 15.32653061,
         18.48979592, 16.12244898, 19.18367347, 16.91836735,
         19.87755102, 17.71428571, 20.57142857, 18.51020408,
         21.26530612, 19.30612245, 21.95918367, 20.10204082,
         22.65306122]],

       [[20.89795918, 23.34693878, 21.69387755, 24.04081633,
         22.48979592, 24.73469388, 23.28571429, 25.42857143,
         24.08163265, 26.12244898, 24.87755102, 26.81632653,
         25.67346939, 27.51020408, 26.46938776, 28.20408163,
         27.26530612, 28.89795918, 28.06122449, 29.59183673,
         28.85714286, 30.28571429, 29.65306122, 30.97959184,
         30.44897959],
        [31.67346939, 31.24489796, 32.36734694, 32.04081633,
         33.06122449, 32.83673469, 33.75510204, 33.63265306,
         34.44897959, 34.42857143, 35.14285714, 35.2244898 ,
         35.83673469, 36.02040816, 36.53061224, 36.81632653,
         37.2244898 , 37.6122449 , 37.91836735, 38.40816327,
         38.6122449 , 39.20408163, 39.30612245, 40.        ,
         40.        ]]])

In [278]:
a=np.random.randn(4,2,1)

In [279]:
a

array([[[ 0.50839624],
        [ 0.21611601]],

       [[-1.85861239],
        [-0.41931648]],

       [[-0.1323289 ],
        [-0.03957024]],

       [[ 0.32600343],
        [-2.04032305]]])

In [280]:
a.ndim

3

In [281]:
a.shape

(4, 2, 1)

In [284]:
np.random.randint(2,5,(4,4))

array([[2, 4, 3, 2],
       [4, 2, 4, 2],
       [4, 3, 2, 2],
       [4, 4, 3, 3]])

In [290]:
a=titanic_data.dtypes

In [291]:
a

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
max_fare         int64
dtype: object

In [294]:
a[2:4]

Pclass     int64
Name      object
dtype: object

In [324]:
titanic_data[titanic_data['Cabin'].isnull()==True]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,max_fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,512
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,512
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,512
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,512
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,512
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,512
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,512
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,512
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,512
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,512

In [318]:
titanic_data.iloc[np.where(a.index)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,max_fare
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,512
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,512
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,512
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,512
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,512
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,512
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,512
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,512
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,512
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,512

In [343]:
titanic_data[(titanic_data['Survived']==1)  & (titanic_data['Sex']=='male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,max_fare
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,512
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S,512
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,512
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C,512
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,512
...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S,512
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C,512
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S,512
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S,512
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,512

In [347]:
titanic_data.iloc[np.where((titanic_data['Survived']==1) & (titanic_data['Sex']=='male'))]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,max_fare
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,512
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S,512
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,512
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C,512
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,512
...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S,512
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C,512
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S,512
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S,512
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,512

In [384]:
np.random.seed(23)
a=pd.DataFrame(np.random.randn(4,5),columns=['x','y','z','u','v'],index=['a','b','c','d'])

In [385]:
a

          x         y         z         u         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [373]:
a.loc[['c','d'],['z','u']]

   z  u
c  5  4
d  3  5

In [379]:
a.iloc[2:,2:4]

   z  u
c  5  4
d  3  5

In [386]:
a

          x         y         z         u         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [395]:
a[a<0]

          x         y         z         u         v
a       NaN       NaN -0.777619       NaN       NaN
b -1.051082 -0.367548 -1.137460 -1.322148       NaN
c -0.347459       NaN       NaN       NaN -1.043450
d -1.009942       NaN       NaN -1.838068 -0.938769

In [409]:
a.columns

Index(['x', 'y', 'z', 'u', 'v'], dtype='object')

In [413]:
a.values[a.values<0]

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [418]:
a.values[a.iloc[0:5]<0]

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [431]:
d=a.values[a<0]
for i in a.columns:
    for j in a.index:
        if a[i][j] in d:
            print(i,'   ',j,'  ',a[i][j])

x     b    -1.0510815639071178
x     c    -0.34745899102186334
x     d    -1.0099418765878465
y     b    -0.3675481161171661
z     a    -0.7776194131918178
z     b    -1.1374596907250272
u     b    -1.3221475225908594
u     d    -1.8380677677579502
v     c    -1.0434500017467254
v     d    -0.9387686311201282

In [421]:
a.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [428]:
a.values<0

array([[False, False,  True, False, False],
       [ True,  True,  True,  True, False],
       [ True, False, False, False,  True],
       [ True, False, False,  True,  True]])